<div class="block-box">
	<div class="block-content">
        <?php echo $this->render('application/left-menu'); ?>
		<div class="main border-left">
			<div class="main-title">
				<h3>Nội thất phòng ngủ</h3>
			</div>
			<div class="list-items margin-top-15">
				<div class="item">
					<div class="item-view">
						<ul class="item-fluid">
							<li class="img">
								<div class="thumbnails">
									<a href="/san-pham/bo-phong-ngu-cao-cap-703/" class="thumbnail">
										<img src="https://www.kymdan.com/attachment.do?file=attachment/49/SYMMETRIC_avatar_384x230_384x288.jpg" title="Bộ phòng ngủ cao cấp 703" alt="Bộ phòng ngủ cao cấp 703">
									</a>
								</div>
							</li>
							<li>
								<h2 class="entry-title">
									<a title="Bộ phòng ngủ cao cấp 703" href="/san-pham/bo-phong-ngu-cao-cap-703/">Bộ phòng ngủ cao cấp 703</a>
								</h2>
							</li>
							<li class="price-sale"> 122,000,000 vnđ</li>
							<li class="price-old"> 125,000,000 vnd</li>
							<li>
								<a style="display:block;line-height:15px;color:#ffffff" rel="nofollow" href="/san-pham/bo-phong-ngu-cao-cap-703/" class="text-right mybutton">
									<i class="fa fa-shopping-cart" aria-hidden="true"></i> Đặt mua
								</a>
							</li>
						</ul>
					</div>
				</div>
				<div class="item">
					<div class="item-view">
						<ul class="item-fluid">
							<li class="img">
								<div class="thumbnails">
									<a href="/san-pham/bo-phong-ngu-cao-cap-703/" class="thumbnail">
										<img src="https://www.kymdan.com/attachment.do?file=attachment/44/bed_light_new(l)_384x288.jpg" title="Bộ phòng ngủ cao cấp 703" alt="Bộ phòng ngủ cao cấp 703">
									</a>
								</div>
							</li>
							<li>
								<h2 class="entry-title">
									<a title="Bộ phòng ngủ cao cấp 703" href="/san-pham/bo-phong-ngu-cao-cap-703/">Bộ phòng ngủ cao cấp 703</a>
								</h2>
							</li>
							<li class="price-sale"> 122,000,000 vnđ</li>
							<li class="price-old"> 125,000,000 vnd</li>
							<li>
								<a style="display:block;line-height:15px;color:#ffffff" rel="nofollow" href="/san-pham/bo-phong-ngu-cao-cap-703/" class="text-right mybutton">
									<i class="fa fa-shopping-cart" aria-hidden="true"></i> Đặt mua
								</a>
							</li>
						</ul>
					</div>
				</div>
				<div class="item">
					<div class="item-view">
						<ul class="item-fluid">
							<li class="img">
								<div class="thumbnails">
									<a href="/san-pham/bo-phong-ngu-cao-cap-703/" class="thumbnail">
										<img src="https://www.kymdan.com/attachment.do?file=attachment/6309/DIAMOND_avatar_384x288.jpg" title="Bộ phòng ngủ cao cấp 703" alt="Bộ phòng ngủ cao cấp 703">
									</a>
								</div>
							</li>
							<li>
								<h2 class="entry-title">
									<a title="Bộ phòng ngủ cao cấp 703" href="/san-pham/bo-phong-ngu-cao-cap-703/">Bộ phòng ngủ cao cấp 703</a>
								</h2>
							</li>
							<li class="price-sale"> 122,000,000 vnđ</li>
							<li class="price-old"> 125,000,000 vnd</li>
							<li>
								<a style="display:block;line-height:15px;color:#ffffff" rel="nofollow" href="/san-pham/bo-phong-ngu-cao-cap-703/" class="text-right mybutton">
									<i class="fa fa-shopping-cart" aria-hidden="true"></i> Đặt mua
								</a>
							</li>
						</ul>
					</div>
				</div>
				<div class="item">
					<div class="item-view">
						<ul class="item-fluid">
							<li class="img">
								<div class="thumbnails">
									<a href="/san-pham/bo-phong-ngu-cao-cap-703/" class="thumbnail">
										<img src="https://www.kymdan.com/attachment.do?file=attachment/500/bed_rainbow(l)_384x288.jpg" title="Bộ phòng ngủ cao cấp 703" alt="Bộ phòng ngủ cao cấp 703">
									</a>
								</div>
							</li>
							<li>
								<h2 class="entry-title">
									<a title="Bộ phòng ngủ cao cấp 703" href="/san-pham/bo-phong-ngu-cao-cap-703/">Bộ phòng ngủ cao cấp 703</a>
								</h2>
							</li>
							<li class="price-sale"> 122,000,000 vnđ</li>
							<li class="price-old"> 125,000,000 vnd</li>
							<li>
								<a style="display:block;line-height:15px;color:#ffffff" rel="nofollow" href="/san-pham/bo-phong-ngu-cao-cap-703/" class="text-right mybutton">
									<i class="fa fa-shopping-cart" aria-hidden="true"></i> Đặt mua
								</a>
							</li>
						</ul>
					</div>
				</div>
				<div class="item">
					<div class="item-view">
						<ul class="item-fluid">
							<li class="img">
								<div class="thumbnails">
									<a href="/san-pham/bo-phong-ngu-cao-cap-703/" class="thumbnail">
										<img src="https://www.kymdan.com/attachment.do?file=attachment/49/SYMMETRIC_avatar_384x230_384x288.jpg" title="Bộ phòng ngủ cao cấp 703" alt="Bộ phòng ngủ cao cấp 703">
									</a>
								</div>
							</li>
							<li>
								<h2 class="entry-title">
									<a title="Bộ phòng ngủ cao cấp 703" href="/san-pham/bo-phong-ngu-cao-cap-703/">Bộ phòng ngủ cao cấp 703</a>
								</h2>
							</li>
							<li class="price-sale"> 122,000,000 vnđ</li>
							<li class="price-old"> 125,000,000 vnd</li>
							<li>
								<a style="display:block;line-height:15px;color:#ffffff" rel="nofollow" href="/san-pham/bo-phong-ngu-cao-cap-703/" class="text-right mybutton">
									<i class="fa fa-shopping-cart" aria-hidden="true"></i> Đặt mua
								</a>
							</li>
						</ul>
					</div>
				</div>
				<div class="item">
					<div class="item-view">
						<ul class="item-fluid">
							<li class="img">
								<div class="thumbnails">
									<a href="/san-pham/bo-phong-ngu-cao-cap-703/" class="thumbnail">
										<img src="https://www.kymdan.com/attachment.do?file=attachment/6368/RULER_avatar_384x288.jpg" title="Bộ phòng ngủ cao cấp 703" alt="Bộ phòng ngủ cao cấp 703">
									</a>
								</div>
							</li>
							<li>
								<h2 class="entry-title">
									<a title="Bộ phòng ngủ cao cấp 703" href="/san-pham/bo-phong-ngu-cao-cap-703/">Bộ phòng ngủ cao cấp 703</a>
								</h2>
							</li>
							<li class="price-sale"> 122,000,000 vnđ</li>
							<li class="price-old"> 125,000,000 vnd</li>
							<li>
								<a style="display:block;line-height:15px;color:#ffffff" rel="nofollow" href="/san-pham/bo-phong-ngu-cao-cap-703/" class="text-right mybutton">
									<i class="fa fa-shopping-cart" aria-hidden="true"></i> Đặt mua
								</a>
							</li>
						</ul>
					</div>
				</div>
				<div class="item">
					<div class="item-view">
						<ul class="item-fluid">
							<li class="img">
								<div class="thumbnails">
									<a href="/san-pham/bo-phong-ngu-cao-cap-703/" class="thumbnail">
										<img src="https://www.kymdan.com/attachment.do?file=attachment/500/bed_rainbow(l)_384x288.jpg" title="Bộ phòng ngủ cao cấp 703" alt="Bộ phòng ngủ cao cấp 703">
									</a>
								</div>
							</li>
							<li>
								<h2 class="entry-title">
									<a title="Bộ phòng ngủ cao cấp 703" href="/san-pham/bo-phong-ngu-cao-cap-703/">Bộ phòng ngủ cao cấp 703</a>
								</h2>
							</li>
							<li class="price-sale"> 122,000,000 vnđ</li>
							<li class="price-old"> 125,000,000 vnd</li>
							<li>
								<a style="display:block;line-height:15px;color:#ffffff" rel="nofollow" href="/san-pham/bo-phong-ngu-cao-cap-703/" class="text-right mybutton">
									<i class="fa fa-shopping-cart" aria-hidden="true"></i> Đặt mua
								</a>
							</li>
						</ul>
					</div>
				</div>
				<div class="item">
					<div class="item-view">
						<ul class="item-fluid">
							<li class="img">
								<div class="thumbnails">
									<a href="/san-pham/bo-phong-ngu-cao-cap-703/" class="thumbnail">
										<img src="https://www.kymdan.com/attachment.do?file=attachment/500/bed_rainbow(l)_384x288.jpg" title="Bộ phòng ngủ cao cấp 703" alt="Bộ phòng ngủ cao cấp 703">
									</a>
								</div>
							</li>
							<li>
								<h2 class="entry-title">
									<a title="Bộ phòng ngủ cao cấp 703" href="/san-pham/bo-phong-ngu-cao-cap-703/">Bộ phòng ngủ cao cấp 703</a>
								</h2>
							</li>
							<li class="price-sale"> 122,000,000 vnđ</li>
							<li class="price-old"> 125,000,000 vnd</li>
							<li>
								<a style="display:block;line-height:15px;color:#ffffff" rel="nofollow" href="/san-pham/bo-phong-ngu-cao-cap-703/" class="text-right mybutton">
									<i class="fa fa-shopping-cart" aria-hidden="true"></i> Đặt mua
								</a>
							</li>
						</ul>
					</div>
				</div>
				<div class="item">
					<div class="item-view">
						<ul class="item-fluid">
							<li class="img">
								<div class="thumbnails">
									<a href="/san-pham/bo-phong-ngu-cao-cap-703/" class="thumbnail">
										<img src="https://www.kymdan.com/attachment.do?file=attachment/6368/RULER_avatar_384x288.jpg" title="Bộ phòng ngủ cao cấp 703" alt="Bộ phòng ngủ cao cấp 703">
									</a>
								</div>
							</li>
							<li>
								<h2 class="entry-title">
									<a title="Bộ phòng ngủ cao cấp 703" href="/san-pham/bo-phong-ngu-cao-cap-703/">Bộ phòng ngủ cao cấp 703</a>
								</h2>
							</li>
							<li class="price-sale"> 122,000,000 vnđ</li>
							<li class="price-old"> 125,000,000 vnd</li>
							<li>
								<a style="display:block;line-height:15px;color:#ffffff" rel="nofollow" href="/san-pham/bo-phong-ngu-cao-cap-703/" class="text-right mybutton">
									<i class="fa fa-shopping-cart" aria-hidden="true"></i> Đặt mua
								</a>
							</li>
						</ul>
					</div>
				</div>
			</div>
		</div>
	</div>
</div>