<div data-view="administrator/group/index">
    <div class="col-item">
        <form method="get">
            <div class="rows" style="border-bottom: none; border-top: 1px solid #ddd">
                <div class="col-lg-2 pull-left" style="margin-top: 25px">
                    <div id="editable-sample_length" class="dataTables_length no-padding">
                        <a class="btn btn-success" href="<?php echo $this->Url('administratorGroup', ['action'=>'create'])?>"><i class="icon-plus-sign-alt"></i> Thêm</a>
                    </div>
                </div>
                <div class="search-product">
                    <div class="search-title">
                        <div class="search-title-block">
                            <input name="search" class="search-product-title" type="text" value="<?php echo !empty($this->params['search']) ? $this->params['search'] : ''?>" placeholder="Tìm kiếm theo tên">
                            <button class="search-products" type="submit">
                                <i class="icon-search"></i>
                            </button>
                        </div>
                    </div>
                </div>
            </div>
            <table style="margin-bottom: 0" class="table table-striped table-bordered table-hover">
                <thead>
                <tr>
                    <th class="center"><span class="icon icon-list"></span> ID</th>
                    <th class="center"><span class="icon icon-list-alt"></span> Group name</th>
                    <th class="center"><span class="icon icon-calendar"> Ngày tạo</th>
                    <th class="center"><span class="icon icon-user"> Người tạo</th>
                    <th class="center"><span class="icon icon-random"></span> Trạng thái</th>
                    <th class="center"><span class="icon icon-gears"></span> Tùy chỉnh</th>
                </tr>
                </thead>
                <tbody>
                <?php if(!empty($this->groups['rows'])):
                    foreach ($this->groups['rows'] as $group):
                        ?>
                        <tr>
                            <td class="center">
                                <b>
                                    <a href="javascript:;">
                                        <?php echo $group['group_id']?>
                                    </a>
                                </b>
                            </td>
                            <td class="center">
                                <b>
                                    <a href="javascript:;">
                                        <?php echo $group['group_name']?>
                                    </a>
                                </b>
                            </td>
                            <td class="center"><?php echo date('Y-m-d', $group['created_date']);?></td>
                            <td class="center"><?php echo empty($this->users[$group['user_created']]) ? '' : $this->users[$group['user_created']]['full_name']?></td>
                            <td class="center">
                                <?php if($group['status'] == APP\Model\Group::GROUP_STATUS_ACTIVE):?>
                                    <a href="javascript:;" data-toggle="tooltip" title="Hoạt động"><i class="ico icon-check"></i></a>
                                <?php else:?>
                                    <a href="javascript:;" data-toggle="tooltip" title="Đang ẩn"><i class="ico icon-remove"></i></a>
                                <?php endif;?>
                            </td>
                            <td class="center">
                                <a class="btn btn-small btn-primary" data-toggle="tooltip" title="Cập nhật" href="<?php echo $this->Url('administratorGroup', ['action'=>'edit', 'id' => $group['group_id']])?>">
                                    <i class="icon icon-edit"></i>
                                </a>
                                <a class="btn btn-small btn-primary permission" data-toggle="tooltip" href="<?php echo $this->Url('administratorPermission', ['action'=>'grant', 'gid' => $group['group_id']])?>" title="Phân quyền">
                                    <i class="icon icon-lock"></i>
                                </a>
                                <a class="delete" data-toggle="tooltip" rel="<?php echo $group['group_id']?>" title="Xóa nhóm">
                                    <i class="icon icon-trash"></i>
                                </a>
                            </td>
                        </tr>
                    <?php endforeach; endif;?>
                </tbody>
            </table>
        </form>
    </div>
</div>