<div class="data-view" data-view="administrator/permission/grant">
    <div class="col-item">
        <form method="get">
            <?php
                if ($this->arrResourceList):
                    foreach ($this->arrResourceList as $arrResource):
                        $strModuleName = strtolower($arrResource['module']);
                        $strControllerName = strtolower($arrResource['controller']);
                        ?>
                        <div class="col-lg-3">
                            <section class="panel">
                                <header class="panel-heading">
                                    <b><?php echo $this->translator($strModuleName . ':' . $strControllerName); ?></b>
                                </header>
                                <div class="panel-body">
                                    <div class="loading">
                                        <div class="loading-icon"></div>
                                    </div>
                                    <div class="actionList" style="height:190px;max-height:190px;overflow-x:scroll;overflow-x:hidden;">
                                        <?php
                                        if ($arrResource['action']):
                                            foreach ($arrResource['action'] as $strAction):
                                                $strResource = $strModuleName . ':' . $strControllerName . ':' . strtolower($strAction);
                                                ?>
                                                <div class="checkbox">
                                                    <label>
                                                        <input type="checkbox" class="actionName" value="<?php echo $strResource; ?>" <?php echo in_array($strResource, $this->arrAllowedResource) ? 'checked="checked"' : ''; ?>>
                                                        <?php echo $this->translator($strResource); ?>
                                                    </label>
                                                </div>
                                            <?php endforeach; ?>
                                        <?php else: ?>
                                            <center>Hiện tại chưa có Action nào</center>
                                        <?php endif; ?>
                                    </div>
                                </div>
                            </section>
                        </div>
                    <?php endforeach; ?>
                <?php endif;
            ?>
        </form>
    </div>
</div>
<script>
    Registry.set('part','<?php echo $this->part;?>');
    Registry.set('id','<?php echo $this->id;?>');
</script>