<div class="rows" data-view="administrator/properties/edit">
    <div class="col-xs-9">
        <div class="widget-box">
            <div class="widget-body">
                <div class="widget-main">
                    <div id="fuelux-wizard-container" class="no-steps-container">
                        <div class="step-content pos-rel">
                            <div class="step-pane active" data-step="1">
                                <h3 class="lighter block green">Nhập thông tin</h3>
                                <form class="form-horizontal" id="sample-form" method="post">
                                    <?php if(!empty($this->params['error'])):?>
                                        <div class="alert alert-danger">
                                            <button type="button" class="close" data-dismiss="alert">
                                                <i class="ace-icon fa fa-times"></i>
                                            </button>
                                            <strong>
                                                <i class="ace-icon fa fa-times"></i>
                                                Oh snap!
                                            </strong>
                                            <?php echo $this->params['error']?>
                                            <br>
                                        </div>
                                    <?php endif;?>
                                    <?php if(!empty($_SESSION['update-properties-success'])):?>
                                        <div class="alert alert-block alert-success">
                                            <button type="button" class="close" data-dismiss="alert">
                                                <i class="ace-icon fa fa-times"></i>
                                            </button>
                                            <p>
                                                Cập nhật thành công!
                                            </p>
                                        </div>
                                        <?php
                                        unset($_SESSION['update-properties-success']);
                                    endif;
                                    ?>
                                    <?php if(!empty($_SESSION['create-properties-success'])):?>
                                        <div class="alert alert-block alert-success">
                                            <button type="button" class="close" data-dismiss="alert">
                                                <i class="ace-icon fa fa-times"></i>
                                            </button>
                                            <p>
                                                Thêm thuộc tính thành công!
                                            </p>
                                        </div>
                                        <?php
                                        unset($_SESSION['create-properties-success']);
                                    endif;
                                    ?>

                                    <div class="form-group">
                                        <label for="inputWarning" class="col-xs-12 col-sm-3 control-label no-padding-right">Tên thuộc tính</label>
                                        <div class="col-xs-12 col-sm-5">
                                            <span class="block input-icon input-icon-right">
                                                <input type="text" class="width-100" name="properties_name" placeholder="Nhập tên thuộc tính"
                                                       value="<?php echo empty($this->params['properties_name']) ? $this->properties['properties_name'] : $this->params['properties_name'];?>">
                                            </span>
                                        </div>
                                    </div>
                                    <hr>
                                    <div class="center">
                                        <button class="btn btn-success" type="submit">
                                            <i class="ace-icon fa fa-save"></i>
                                            Cập nhật
                                        </button>
                                    </div>
                                </form>
                            </div>
                        </div>
                    </div
                </div><!-- /.widget-main -->
            </div><!-- /.widget-body -->
        </div>
    </div>
</div>