<div class="rows" data-view="administrator/properties/index">
    <div class="col-xs-12">
        <form method="get" class="form-search">
            <div class="col-xs-12" style="margin-bottom: 10px">
                <div class="col-xs-6">
                    <a class="btn btn-xs btn-danger remove-all" href="javascript:;" style="margin-right: 5px">
                        <i class="fa fa-trash "></i> Xóa
                    </a>
                    <a class="btn btn-xs btn-success" href="<?php echo $this->Url('administratorProduct', ['action'=>'create'])?>">
                        <i class="ace-icon fa fa-plus">
                            Thêm
                        </i>
                    </a>
                </div>
                <div class="col-xs-4 col-xs-offset-2">
                    <span class="input-icon">
                        <input type="text" name="search" placeholder="Tìm kiếm ..." class="nav-search-input" autocomplete="off"
                               value="<?php echo (empty($this->params['search'])) ? '' : $this->params['search'];?>"
                        >
                    </span>
                    <button type="submit" class="btn btn-xs btn-primary">
                        <i class="ace-icon fa fa-search"></i> Tìm
                    </button>
                </div>
            </div>
            <table id="simple-table" class="table  table-bordered table-hover">
                <thead>
                <tr>
                    <th class="center"><span class="fa fa-list"> ID</th>
                    <th class="center"><span class="fa fa-list-alt"></span> Tên</th>
                    <th class="center"><span class="fa fa-calendar"></span> Ngày tạo</th>
                    <th class="center"><span class="fa fa-user"></span> Người tạo</th>
                    <th class="center"><span class="fa fa-gears"></span> Tùy chỉnh</th>
                </tr>
                </thead>
                <tbody>
                <?php if(!empty($this->properties['rows'])):
                    foreach ($this->properties['rows'] as $rows):
                        ?>
                        <tr>
                            <td class="center">
                                <b>
                                    <a href="javascript:;">
                                        <?php echo $rows['id']?>
                                    </a>
                                </b>
                            </td>
                            <td class="text-center">
                                <?php
                                echo $rows['properties_name']
                                ?>
                            </td>
                            <td class="center"><?php echo date('Y-m-d', $rows['created_date']);?></td>
                            <td class="center"><?php echo empty($this->users[$rows['user_created']]) ? '' : $this->users[$rows['user_created']]['full_name']?></td>
                            <td class="center">
                                <div class="hidden-sm hidden-xs btn-group">
                                    <a class="btn btn-xs btn-info" data-toggle="tooltip" title="Cập nhật" href="<?php echo $this->Url('administratorProperties', ['action'=>'edit', 'id' =>$rows['id']])?>">
                                        <i class="ace-icon fa fa-pencil bigger-120"></i>
                                    </a>
                                    <a class="btn btn-xs btn-danger delete" data-toggle="tooltip" rel="<?php echo $rows['id']?>" title="Xóa thuộc tính"><i class="ace-icon fa fa-trash-o bigger-120"></i></a>
                                </div>
                            </td>
                        </tr>
                    <?php endforeach; endif;?>
                </tbody>
            </table>
            <?php
            $params = $this->params;
            $params['controller'] = $params['strController'];
            $paging = $this->pagingText($params);
            if(!empty($paging)){
                echo $paging;
            }
            ?>
        </form>
    </div>
</div>