<div class="data-view" data-view="administrator/invoice/create">
    <div class="col-xs-12">
        <!-- PAGE CONTENT BEGINS -->
        <div class="space-6"></div>

        <div class="row">
            <div class="col-sm-12">
                <div class="widget-box transparent">
                    <div class="widget-header widget-header-large">
                        <h3 class="widget-title grey lighter">
                            <i class="ace-icon fa fa-leaf green"></i>
                            Tạo đơn thuốc
                        </h3>

                        <div class="widget-toolbar no-border invoice-info">
                            <span class="invoice-info-label">Mã:</span>
                            <span class="red">#121212</span>

                            <br>
                            <span class="invoice-info-label">Ngày:</span>
                            <span class="blue"><?php echo date('d/m/Y')?></span>
                        </div>

                        <div class="widget-toolbar hidden-480">
                            <a href="#">
                                <i class="ace-icon fa fa-print"></i>
                            </a>
                        </div>
                    </div>

                    <div class="widget-body">
                        <div class="widget-main padding-24">
                            <div class="row">
                                <div class="col-sm-6">
                                    <div class="row">
                                        <div class="col-xs-11 label label-lg label-info arrowed-in arrowed-right">
                                            <b>Thông tin khách hàng</b>
                                        </div>
                                    </div>

                                    <div class="rows">
                                        <div class="col-xs-3">
                                            <i class="ace-icon fa fa-caret-right blue"></i>Tên
                                        </div>
                                        <div class="col-xs-9">
                                            <div class="col-sm-8 col-md-7">
                                                <input id="tags" type="text" class="form-control ui-autocomplete-input" autocomplete="off">
                                            </div>
                                        </div>
                                        <div class="col-xs-3">
                                            <i class="ace-icon fa fa-caret-right blue"></i>Số điện thoại
                                        </div>
                                        <div class="col-xs-9">
                                            : 0973531618
                                        </div>
                                        <div class="col-xs-3">
                                            <i class="ace-icon fa fa-caret-right blue"></i>Địa chỉ
                                        </div>
                                        <div class="col-xs-9">
                                            : Đội 8
                                        </div>
                                    </div>
                                </div><!-- /.col -->

<!--                                <div class="col-sm-6">-->
<!--                                    <div class="row">-->
<!--                                        <div class="col-xs-11 label label-lg label-success arrowed-in arrowed-right">-->
<!--                                            <b>Customer Info</b>-->
<!--                                        </div>-->
<!--                                    </div>-->
<!--                                    <div>-->
<!--                                        <ul class="list-unstyled  spaced">-->
<!--                                            <li>-->
<!--                                                <i class="ace-icon fa fa-caret-right green"></i>Street, City-->
<!--                                            </li>-->
<!---->
<!--                                            <li>-->
<!--                                                <i class="ace-icon fa fa-caret-right green"></i>Zip Code-->
<!--                                            </li>-->
<!---->
<!--                                            <li>-->
<!--                                                <i class="ace-icon fa fa-caret-right green"></i>State, Country-->
<!--                                            </li>-->
<!---->
<!--                                            <li class="divider"></li>-->
<!---->
<!--                                            <li>-->
<!--                                                <i class="ace-icon fa fa-caret-right green"></i>-->
<!--                                                Contact Info-->
<!--                                            </li>-->
<!--                                        </ul>-->
<!--                                    </div>-->
<!--                                </div><!-- /.col -->
                            </div><!-- /.row -->

                            <div class="space"></div>

                            <form method="post">
                            <div>
                                <div class="pull-right" style="margin-bottom: 10px">
                                    <a class="btn btn-xs btn-primary add-product">
                                        <i class="ace-icon fa fa-plus-circle"></i>
                                        Thêm
                                    </a>
                                </div>

                                    <table class="table table-striped table-bordered">
                                    <thead>
                                    <tr>
                                        <th class="center">STT</th>
                                        <th class="center" width="200px">Thuốc</th>
                                        <th class="center">ĐVT</th>
                                        <th class="center">Mô tả</th>
                                        <th class="center">Số lượng</th>
                                        <th class="center">Giá bán (VNĐ)</th>
                                        <th class="center">Giảm giá (%)</th>
                                        <th class="center">Tổng tiền (VNĐ)</th>
                                        <th class="center" width="50px">Chức năng</th>
                                    </tr>
                                    </thead>
                                    <tbody>
                                    </tbody>
                                </table>

                                <div class="hr hr8 hr-double hr-dotted"></div>
                                <div class="row">
                                    <div class="col-sm-5 pull-right">
                                        <h4 class="pull-right">
                                            Tổng cộng :
                                            <span class="red sum_total_price">0</span> VNĐ
                                        </h4>
                                    </div>
                                    <div class="col-sm-7 pull-left"></div>
                                </div>
                            </div>
                            <div class="center">
                                <button type="submit" class="btn btn-xs btn-success">
                                    <i class="ace-icon fa fa-save"></i> Xác nhận
                                </button>
                            </div>
                            </form>

<!--                            <div class="hr hr8 hr-double hr-dotted"></div>-->
<!--                            <div class="space-6"></div>-->
<!--                            <div class="well">-->
<!--                                Cảm ơn bạn đã sử dụng dịch vụ của chúng tôi-->
<!--                            </div>-->
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <!-- PAGE CONTENT ENDS -->
    </div>
</div>
<script type="text/javascript">
    Registry.set('WAREHOUSES', <?php echo json_encode($this->warehouses)?>);
</script>