<div class="data-view" data-view="administrator/invoice/create">
    <div class="page-content">
        <form name="form" class="form-search" method="post">
            <div style="margin-bottom: 10px; border-radius: 0 !important;border: 1px solid #ddd;
    border-collapse: separate;">
                <div style=" width:400px; padding: 8px 20px 2px;margin: 0;">
                    <span>
                        Tên khách hàng
                    </span>
                </div>
            </div>
            <div>
                <table style="margin-bottom: 0" class="table table-striped table-bordered table-hover">
                <thead>
                <tr class="">
                    <th class="center"> STT</th>
                    <th class="center"> Thuốc</th>
                    <th class="center"> ĐVT </th>
                    <th class="center"> Số lượng</th>
                    <th class="center"> Đơn giá</th>
                    <th class="center"> Thành tiền</th>
                    <th class="center"> % CK</th>
                    <th class="center"> Thực thu</th>
                    <th class="center"> Lô</th>
                    <th class="center"> Hạn dùng</th>
                </tr>
                </thead>
                <tbody>
                    <tr>
                        <td class="center" >1</td>
                        <td width="350px">
                            <div>
                                <select name="warehouse_id[]" class="select-picker" style="width: 300px" data-live-search="true">
                                    <?php foreach ($this->warehouses['rows'] as $row):?>
                                        <option data-toggle='tooltip' value="<?php echo $row['warehouse_id']?>" data-stock="<?php echo $row['stock']?>"
                                                data-title="<?php echo $row['product_name']?> - Loại : <?php echo $row['properties_name']?> - Số lô : <?php echo $row['production_batch'];?> - Hiệu :<?php echo $row['brand_name']?> - Còn : <?php echo $row['stock']?> - NSX : <?php echo date('d-m-Y',$row['nsx'])?> - HSD : <?php echo date('d-m-Y',$row['hsd'])?>"
                                        >
                                            <?php echo $row['product_name']?> - Loại : <?php echo $row['properties_name']?> - Số lô : <?php echo $row['production_batch'];?> - Hiệu :<?php echo $row['brand_name']?> - Còn : <?php echo $row['stock']?>
                                        </option>
                                    <?php endforeach;?>
                                </select>
                            </div>
                        </td>
                        <td class="center">
                            <select style="width: 80px">
                                <option value="1">1</option>
                                <option value="2">2</option>
                                <option value="3">3</option>
                                <option value="4">4</option>
                                <option value="5">5</option>
                            </select>
                        </td>
                        <td class="center"></td>
                        <td class="center"></td>
                        <td class="center"></td>
                        <td class="center"></td>
                        <td class="center"></td>
                        <td class="center"></td>
                        <td class="center"></td>
                    </tr>
                    <tr>
                        <td class="center" colspan="5"><b>Tổng</b></td>
                        <td class="center"></td>
                        <td class="center"></td>
                        <td class="center" colspan="3"></td>
                    </tr>
                </tbody>
            </table>
            </div>
        </form>
    </div>
</div>