<?php
    $params = $this->params;
    $warehouses = $this->warehouses;
    $current_warehouse_id = empty($params['current_warehouse_id']) ? '' : $params['current_warehouse_id'];
?>
<div class="rows">
    <div class="col-xs-12">
        <div class="col-xs-3">
            <select class="form-control" name="select-warehouse">
                <?php foreach ($warehouses['rows'] as $row):?>
                    <option value="<?php echo $row['warehouse_id']?>"></option>
                <?php endforeach;?>
            </select>
        </div>
        <div class="col-xs-3">
            <input name="choose-quantity">
<!--            <select class="form-control">-->
<!--                --><?php //foreach ($warehouses['rows'] as $row):?>
<!--                    <option value="--><?php //echo $row['warehouse_id']?><!--"></option>-->
<!--                --><?php //endforeach;?>
<!--            </select>-->
        </div>
    </div>
    <div class="col-xs-12">
        <button class="">

        </button>
    </div>
</div>
<div>

</div>
