<div data-view="administrator/product/index">
    <div class="col-item">
        <form method="get">
            <div class="rows" style="border-bottom: none; border-top: 1px solid #ddd">
                <div class="search-product">
                    <div class="col-lg-2 pull-left" style="margin-top: 25px">
                        <div id="editable-sample_length" class="dataTables_length no-padding">
                            <a class="btn btn-success" href="<?php echo $this->Url('administratorProduct', ['action'=>'create'])?>"><i class="icon-plus-sign-alt"></i> Thêm</a>
                            <a class="btn btn-danger remove-all" href="javascript:;"><i class="icon-trash "></i> Xóa</a>
                        </div>
                    </div>
                    <div class="search-title">
                        <div class="search-title-block">
                            <input class="search-product-title" type="text" name="search" placeholder="Tìm kiếm theo tên" value="<?php echo !empty($this->params['search']) ? $this->params['search'] : ''?>" placeholder="Tìm kiếm theo tên">
                            <button class="search-products" type="submit">
                                <i class="icon-search"></i>
                            </button>
                        </div>
                    </div>
                </div>
            </div>
            <table style="margin-bottom: 0" class="table table-striped table-bordered table-hover">
                <thead>
                <tr>
                    <th class="center"> # </th>
                    <th class="center"><span class="icon icon-list-alt"></span> Tên thuốc</th>
                    <th class="center"><span class="icon icon-barcode"></span> Mã</th>
                    <th class="center">Danh mục</th>
                    <th class="center">Nhãn hiệu</th>
                    <th class="center">Xuất xứ</th>
                    <th class="center"><span class="icon icon-dollar"></span> Giá bán (VNĐ)</th>
                    <th class="center">Giá gốc (VNĐ)</th>
                    <th class="center"><span class="icon icon-calendar"></span> Ngày tạo</th>
                    <th class="center"><span class="icon icon-user"></span> Người tạo</th>
<!--                    <th class="center"><span class="icon icon-random"></span> Trạng thái</th>-->
                    <th class="center"><span class="icon icon-gears"></span> Tùy chỉnh</th>
                </tr>
                </thead>
                <tbody>
                <?php if(!empty($this->products)):
                    foreach ($this->products['rows'] as $row):
                    ?>
                    <tr>
                        <td class="center"><input type="checkbox" name="data-id" class="input" value="<?php echo $row['product_id']?>"></td>
                        <td><a href="<?php echo $this->Url('products', ['name'=>$row['product_slug']])?>" target="_blank"><b><?php echo $row['product_name'];?></b></a></td>
                        <td class="center"><b><?php echo $row['product_code'];?></b></td>
                        <td class="center"><?php echo $this->categories[$row['cate_id']]['cate_name'];?></td>
                        <td class="center"><?php echo empty($this->brands[$row['brand_id']]['brand_name']) ? 'Không xác định' : $this->brands[$row['brand_id']]['brand_name'];?></td>
                        <td class="center"><?php echo empty($this->brands[$row['brand_id']]) || empty($this->countries[$this->brands[$row['brand_id']]['country_id']]['country_name']) ? 'Không xác định' : $this->countries[$this->brands[$row['brand_id']]['country_id']]['country_name'];?></td>
                        <td class="center"><b class="red"><?php echo number_format($row['price']);?></b></td>
                        <td class="center"><?php echo number_format($row['price_cost']);?></td>
                        <td class="center"><?php echo date('Y-m-d',$row['created_date']);?></td>
                        <td class="center"><?php echo $this->users[$row['user_created']]['full_name'];?></td>
<!--                        <td class="center">--><?php //echo $this->renderStatus[$row['status']];?><!--</td>-->
                        <td class="center">
<!--                            <a data-toggle="tooltip" title="Xem sản phẩm" class="btn btn-small btn-primary" target="_blank" href="--><?php //echo $this->Url('products', ['name'=>$row['product_slug']])?><!--">-->
<!--                                <i class="icon icon-eye-open"></i>-->
<!--                            </a>-->
                            <a data-toggle="tooltip" title="Cập nhật" class="btn btn-small btn-primary" href="<?php echo $this->Url('administratorProduct', ['action'=>'edit', 'id' => $row['product_id']])?>">
                                <i class="icon icon-edit"></i>
                            </a>
                        </td>
                    </tr>
                <?php endforeach; endif;?>
                </tbody>
            </table>
            <?php
            if(!empty($this->products)) {
                $params = $this->params;
                $params['controller'] = $params['strController'];
                $paging = $this->pagingText($params);
                if (!empty($paging)) {
                    echo $paging;
                }
            }
            ?>
        </form>
    </div>
</div>