<a href="#" id="btn-scroll-up" class="btn-scroll-up btn btn-small btn-inverse">
    <i class="icon-double-angle-up icon-only bigger-110"></i>
</a>

<!--basic scripts-->
<script type="text/javascript">
    if ("ontouchend" in document) document.write("<script src='<?php echo STATIC_URL; ?>assets/js/jquery.mobile.custom.min.js'>" + "<" + "/script>");
</script>
<script src="<?php echo STATIC_URL; ?>assets/js/bootstrap.min.js"></script>

<script src="<?php echo STATIC_URL; ?>assets/js/jquery-ui-1.10.3.custom.min.js"></script>
<script src="<?php echo STATIC_URL; ?>assets/js/jquery.ui.touch-punch.min.js"></script>
<script src="<?php echo STATIC_URL; ?>assets/js/bootbox.min.js"></script>
<!--ace scripts-->

<script src="<?php echo STATIC_URL; ?>assets/js/ace-elements.min.js"></script>
<script src="<?php echo STATIC_URL; ?>assets/js/ace.min.js"></script>