<?php
$module = MODULE;
$controller = CONTROLLER;
$action = ACTION;
?>
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8"/>
    <title>Dashboard - Admin</title>
    <meta name="description" content="overview &amp; stats"/>
    <meta name="viewport" content="width=device-width, initial-scale=1.0"/>

    <!--basic styles-->
    <link href="<?php echo STATIC_URL; ?>assets/css/bootstrap.min.css" rel="stylesheet"/>
    <link href="<?php echo STATIC_URL; ?>assets/css/bootstrap-responsive.min.css" rel="stylesheet"/>
    <link rel="stylesheet" href="<?php echo STATIC_URL; ?>assets/css/font-awesome.min.css"/>

    <link href="<?php echo STATIC_URL; ?>css/css.css" rel="stylesheet"/>

    <!--ace styles-->
    <link rel="stylesheet" href="<?php echo STATIC_URL; ?>assets/css/ace.min.css"/>
    <link rel="stylesheet" href="<?php echo STATIC_URL; ?>assets/css/ace-responsive.min.css"/>
    <link rel="stylesheet" href="<?php echo STATIC_URL; ?>assets/css/ace-skins.min.css"/>

    <!--[if lte IE 8]>
    <link rel="stylesheet" href="<?php echo STATIC_URL; ?>assets/css/ace-ie.min.css"/>
    <![endif]-->
    <script src="<?php echo STATIC_URL; ?>js/libs/jquery/jquery-2.2.4.min.js"></script>
    <script type="application/javascript" src="<?php echo STATIC_URL; ?>js/main.js"></script>
    <script type="application/javascript" src="<?php echo STATIC_URL; ?>js/libs/editor/ckeditor.js"
            charset="utf-8"></script>
    <link rel="stylesheet" href="<?php echo STATIC_URL; ?>css/admin-custom-theme.css"/>
    <link rel="stylesheet" href="<?php echo STATIC_URL; ?>css/admin.css"/>
    <link rel="stylesheet" href="<?php echo STATIC_URL; ?>css/administrator.css"/>
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8"/>
</head>
<body>
<?php echo $this->render('administrator/header'); ?>
<div class="main-container container-fluid">
    <?php echo $this->render('administrator/left_menu'); ?>
    <?php if ($controller != 'index'): ?>
        <div class="main-content">
            <div class="breadcrumbs" id="breadcrumbs">
                <ul class="breadcrumb">
                    <li>
                        <i class="icon-home home-icon"></i>
                        <a target="_blank" href="<?php echo SITE_URL; ?>">Trang chủ</a>
                    </li>
                </ul>
            </div>
            <div class="page-content">
                <div class="page-header position-relative" style="margin-bottom: 0">
                    <h1 class="header-title-top">
                        <small>
                            <?php echo $this->translator($module . ':'. $controller); ?>
                            <i class="icon-double-angle-right"></i>
                            <?php echo $this->translator($module . ':' . $controller . ':' . $action); ?>
                        </small>
                    </h1>
                </div>
            </div>
            <?php echo $this->layout()->content; ?>
        </div>
    <?php endif; ?>
</div>
<?php echo $this->render('administrator/footer'); ?>
<script type="application/javascript">
    MVC.setup({
        css_url: '<?php echo STATIC_URL; ?>/css',
        module_url: '<?php echo STATIC_URL; ?>/js/modules',
        library_url: '<?php echo STATIC_URL; ?>/js/libs',
        model_url: '<?php echo STATIC_URL; ?>/js/models',
        debug: 'true',
        cache: false
    });
    Registry.set('SITE_URL', '<?php echo SITE_URL; ?>');
    Registry.set('STATIC_URL', '<?php echo STATIC_URL; ?>');
</script>
<script type="application/javascript" src="<?php echo STATIC_URL; ?>/js/modules/administrator/layout.js"></script>
</body>
</html>
