<?php
$module = MODULE;
$controller = CONTROLLER;
$action = ACTION;
?>
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8"/>
    <title>Quản lý thuốc - ChienNN</title>

    <meta name="description" content="overview &amp; stats"/>
    <meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0"/>

    <!-- bootstrap & fontawesome -->
    <link rel="stylesheet" href="<?php echo STATIC_URL; ?>assets/css/bootstrap.min.css"/>
    <link rel="stylesheet" href="<?php echo STATIC_URL; ?>assets/font-awesome/4.5.0/css/font-awesome.min.css"/>

    <!-- ace styles -->
    <link rel="stylesheet" href="<?php echo STATIC_URL; ?>assets/css/ace.min.css" class="ace-main-stylesheet"
          id="main-ace-style"/>
<!--    <link rel="stylesheet" href="--><?php //echo STATIC_URL; ?><!--/css/main.css">-->
    <!-- ace settings handler -->
    <script src="<?php echo STATIC_URL; ?>assets/js/ace-extra.min.js"></script>
    <script src="<?php echo STATIC_URL; ?>assets/js/jquery-2.1.4.min.js"></script>
    <script type="application/javascript" src="<?php echo STATIC_URL; ?>js/main.js"></script>
</head>

<body class="no-skin">
<div class="main-container ace-save-state" id="main-container">
    <?php echo $this->render('administrator/header'); ?>
    <script type="text/javascript">
        try {
            ace.settings.loadState('main-container')
        } catch (e) {
        }
    </script>
    <?php echo \My\Minifier\HtmlMin::minify($this->render('administrator/left_menu')); ?>
    <div class="main-content">
        <div class="main-content-inner" style="margin-bottom:100px">
            <div class="breadcrumbs ace-save-state" id="breadcrumbs">
                <ul class="breadcrumb">
                    <li>
                        <i class="ace-icon fa fa-home home-icon"></i>
                        <a href="<?php echo $this->Url('administrator')?>">Home</a>
                    </li>
                    <li class="active"><?php echo $this->translator($module . ':' . $controller . ':' . $action); ?></li>
                </ul>
            </div>
            <div class="page-content">
                <?php echo \My\Minifier\HtmlMin::minify($this->layout()->content); ?>
            </div><!-- /.page-content -->
        </div>
    </div><!-- /.main-content -->
    <?php echo \My\Minifier\HtmlMin::minify($this->render('administrator/footer')); ?>
</div><!-- /.main-container -->


<script src="<?php echo STATIC_URL; ?>js/libs/editor/ckeditor.js"></script>

<!--<script type="application/javascript" src="--><?php //echo STATIC_URL; ?><!--js/libs/editor/ckeditor.js" charset="utf-8"></script>-->

<script src="<?php echo STATIC_URL; ?>assets/js/bootstrap.min.js"></script>
<script src="<?php echo STATIC_URL; ?>assets/js/jquery-ui.min.js"></script>
<script src="<?php echo STATIC_URL; ?>assets/js/jquery-ui.custom.min.js"></script>
<script src="<?php echo STATIC_URL; ?>assets/js/jquery.ui.touch-punch.min.js"></script>
<script src="<?php echo STATIC_URL; ?>assets/js/ace-elements.min.js"></script>
<script src="<?php echo STATIC_URL; ?>assets/js/ace.min.js"></script>


<script type="application/javascript">
    MVC.setup({
        css_url: '<?php echo STATIC_URL; ?>/css',
        module_url: '<?php echo STATIC_URL; ?>/js/modules',
        library_url: '<?php echo STATIC_URL; ?>/js/libs',
        model_url: '<?php echo STATIC_URL; ?>/js/models',
        debug: <?php echo APPLICATION_ENV == 'development' ? 'true' : 'false' ?>,
        cache: <?php echo APPLICATION_ENV == 'development' ? 'false' : 'true' ?>,
        version : '<?php echo APPLICATION_ENV == 'production' ? STATIC_VERSION : 'v1'; ?>'
    });
    Registry.set('SITE_URL', '<?php echo SITE_URL; ?>');
    Registry.set('STATIC_URL', '<?php echo STATIC_URL; ?>');
</script>
</body>
</html>
