<?php
$module = MODULE;
$controller = CONTROLLER;
$action = ACTION;
$permission = json_decode(PERMISSION, true);
$per_controller = $per_controller_action = [];
if (!empty($permission)) {
    foreach ($permission as $item) {
        if (!in_array($item['controller'], $per_controller)) {
            $per_controller[] = $item['controller'];
        }

        $per_controller_action[$item['controller']][] = $item['action'];
    }
}?>
<div id="sidebar" class="sidebar responsive ace-save-state" data-sidebar="true" data-sidebar-scroll="true" data-sidebar-hover="true">
    <script type="text/javascript">
        try{ace.settings.loadState('sidebar')}catch(e){}
    </script>
    <ul class="nav nav-list" style="top: 0px;">
        <?php if (IS_ADMIN || in_array('category', $per_controller)) : ?>
            <li class="<?php if ($controller == 'category') : ?>active open<?php endif; ?>">
                <a href="#" class="dropdown-toggle">
                    <i class="menu-icon fa fa-list"></i>
                    <span class="menu-text"> Danh mục </span>
                    <b class="arrow fa fa-angle-down"></b>
                </a>
                <b class="arrow"></b>
                <ul class="submenu">
                    <?php if (IS_ADMIN || in_array('create', $per_controller_action['category'])): ?>
                        <li <?php echo $controller == 'category' && $action == 'create' ? 'class="active"' : ''; ?>>
                            <a href="<?php echo $this->Url('administratorCategory', ['action'=>'create']);?>">
                                <i class="menu-icon fa fa-angle-double-right"></i>
                                Tạo mới
                            </a>
                            <b class="arrow"></b>
                        </li>
                    <?php endif; ?>
                    <?php if (IS_ADMIN || in_array('index', $per_controller_action['category'])): ?>
                        <li <?php echo $controller == 'category' && $action == 'index' ? 'class="active"' : ''; ?> >
                            <a href="<?php echo $this->Url('administratorCategory')?>">
                                <i class="menu-icon fa fa-angle-double-right"></i>
                                Danh sách
                            </a>
                            <b class="arrow"></b>
                        </li>
                    <?php endif; ?>
                </ul>
            </li>
        <?php endif; ?>
        <?php if (IS_ADMIN || in_array('brand', $per_controller)) : ?>
            <li class="<?php if ($controller == 'brand') : ?>active open<?php endif; ?>">
                <a href="#" class="dropdown-toggle">
                    <i class="menu-icon fa fa-fire"></i>
                    <span class="menu-text"> Nhãn hiệu </span>
                    <b class="arrow fa fa-angle-down"></b>
                </a>
                <b class="arrow"></b>
                <ul class="submenu">
                    <?php if (IS_ADMIN || in_array('create', $per_controller_action['brand'])): ?>
                        <li <?php echo $controller == 'brand' && $action == 'create' ? 'class="active"' : ''; ?> >
                            <a href="<?php echo $this->Url('administratorBrand', ['action'=>'create']);?>">
                                <i class="menu-icon fa fa-angle-double-right"></i>
                                Tạo mới
                            </a>
                            <b class="arrow"></b>
                        </li>
                    <?php endif; ?>
                    <?php if (IS_ADMIN || in_array('index', $per_controller_action['brand'])): ?>
                        <li <?php echo $controller == 'brand' && $action == 'index' ? 'class="active"' : ''; ?> >
                            <a href="<?php echo $this->Url('administratorBrand')?>">
                                <i class="menu-icon fa fa-angle-double-right"></i>
                                Danh sách
                            </a>
                        </li>
                    <?php endif; ?>
                </ul>
            </li>
        <?php endif; ?>
        <?php if (IS_ADMIN || in_array('properties', $per_controller)) : ?>
            <li class="<?php if ($controller == 'properties') : ?>active open<?php endif; ?>">
                <a href="#" class="dropdown-toggle">
                    <i class="menu-icon fa fa-adjust"></i>
                    <span class="menu-text"><?php echo $this->translator('properties')?></span>
                    <b class="arrow fa fa-angle-down"></b>
                </a>
                <b class="arrow"></b>
                <ul class="submenu">
                    <?php if (IS_ADMIN || in_array('create', $per_controller_action['properties'])): ?>
                        <li <?php echo $controller == 'properties' && $action == 'create' ? 'class="active"' : ''; ?> >
                            <a href="<?php echo $this->Url('administratorProperties', ['action'=>'create'])?>">
                                <i class="menu-icon fa fa-angle-double-right"></i>
                                Tạo mới
                            </a>
                            <b class="arrow"></b>
                        </li>
                    <?php endif; ?>
                    <?php if (IS_ADMIN || in_array('index', $per_controller_action['properties'])): ?>
                        <li <?php echo $controller == 'properties' && $action == 'index' ? 'class="active"' : ''; ?> >
                            <a href="<?php echo $this->Url('administratorProperties')?>">
                                <i class="menu-icon fa fa-angle-double-right"></i>
                                Danh sách
                            </a>
                        </li>
                    <?php endif; ?>
                </ul>
            </li>
        <?php endif; ?>
        <?php if (IS_ADMIN || in_array('product', $per_controller)) : ?>
            <li class="<?php if ($controller == 'product') : ?>active open<?php endif; ?>">
                <a href="#" class="dropdown-toggle">
                    <i class="menu-icon fa fa-leaf"></i>
                    <span class="menu-text"> Thuốc </span>
                    <b class="arrow fa fa-angle-down"></b>
                </a>
                <b class="arrow"></b>
                <ul class="submenu">
                    <?php if (IS_ADMIN || in_array('create', $per_controller_action['product'])): ?>
                        <li <?php echo $controller == 'product' && $action == 'create' ? 'class="active"' : ''; ?> >
                            <a href="<?php echo $this->Url('administratorProduct', ['action'=>'create'])?>">
                                <i class="menu-icon fa fa-angle-double-right"></i>
                                Thêm thuốc mới
                            </a>
                            <b class="arrow"></b>
                        </li>
                    <?php endif; ?>
                    <?php if (IS_ADMIN || in_array('index', $per_controller_action['product'])): ?>
                        <li <?php echo $controller == 'product' && $action == 'index' ? 'class="active"' : ''; ?> >
                            <a href="<?php echo $this->Url('administratorProduct')?>">
                                <i class="menu-icon fa fa-angle-double-right"></i>
                                Danh sách
                            </a>
                        </li>
                    <?php endif; ?>
                </ul>
            </li>
        <?php endif; ?>

        <?php if (IS_ADMIN || in_array('warehouse', $per_controller)) : ?>
            <li class="<?php if ($controller == 'warehouse') : ?>active open<?php endif; ?>">
                <a href="#" class="dropdown-toggle">
                    <i class="menu-icon fa fa-home"></i>
                    <span class="menu-text"> Quản lý kho </span>
                    <b class="arrow fa fa-angle-down"></b>
                </a>
                <b class="arrow"></b>
                <ul class="submenu">
                    <?php if (IS_ADMIN || in_array('create', $per_controller_action['warehouse'])): ?>
                        <li <?php echo $controller == 'warehouse' && $action == 'create' ? 'class="active"' : ''; ?> >
                            <a href="<?php echo $this->Url('administratorWarehouse', ['action'=>'create'])?>">
                                <i class="menu-icon fa fa-angle-double-right"></i>
                                Nhập thuốc mới
                            </a>
                            <b class="arrow"></b>
                        </li>
                    <?php endif; ?>
                    <?php if (IS_ADMIN || in_array('index', $per_controller_action['warehouse'])): ?>
                        <li <?php echo $controller == 'warehouse' && $action == 'index' ? 'class="active"' : ''; ?> >
                            <a href="<?php echo $this->Url('administratorWarehouse')?>">
                                <i class="menu-icon fa fa-angle-double-right"></i>
                                Danh sách nhập
                            </a>
                        </li>
                    <?php endif; ?>

                    <?php if (IS_ADMIN || in_array('expire', $per_controller_action['warehouse'])): ?>
                        <li <?php echo $controller == 'warehouse' && $action == 'expire' ? 'class="active"' : ''; ?> >
                            <a href="<?php echo $this->Url('administratorWarehouse', ['action'=>'expire'])?>">
                                <i class="menu-icon fa fa-angle-double-right"></i>
                                Danh thuốc sắp hết hạn
                            </a>
                        </li>
                    <?php endif; ?>

                    <?php if (IS_ADMIN || in_array('expired', $per_controller_action['warehouse'])): ?>
                        <li <?php echo $controller == 'warehouse' && $action == 'expired' ? 'class="active"' : ''; ?> >
                            <a href="<?php echo $this->Url('administratorWarehouse', ['action'=>'expired'])?>">
                                <i class="menu-icon fa fa-angle-double-right"></i>
                                Danh thuốc hết hạn
                            </a>
                        </li>
                    <?php endif; ?>
                </ul>
            </li>
        <?php endif; ?>

<!--        --><?php //if (IS_ADMIN || in_array('user', $per_controller)) : ?>
<!--            <li class="--><?php //if ($controller == 'user') : ?><!--active open--><?php //endif; ?><!--">-->
<!--                <a href="#" class="dropdown-toggle">-->
<!--                    <i class="menu-icon fa fa-user"></i>-->
<!--                    <span class="menu-text"> Người dùng </span>-->
<!--                    <b class="arrow fa fa-angle-down"></b>-->
<!--                </a>-->
<!--                <b class="arrow"></b>-->
<!--                <ul class="submenu">-->
<!--                    --><?php //if (IS_ADMIN || in_array('create', $per_controller_action['user'])): ?>
<!--                        <li --><?php //echo $controller == 'user' && $action == 'create' ? 'class="active"' : ''; ?><!-- >-->
<!--                            <a href="--><?php //echo $this->Url('administratorUser', ['action'=>'create'])?><!--">-->
<!--                                <i class="menu-icon fa fa-angle-double-right"></i>-->
<!--                                Người dùng mới-->
<!--                            </a>-->
<!--                        </li>-->
<!--                    --><?php //endif; ?>
<!--                    --><?php //if (IS_ADMIN || in_array('index', $per_controller_action['user'])): ?>
<!--                        <li --><?php //echo $controller == 'user' && $action == 'index' ? 'class="active"' : ''; ?><!-- >-->
<!--                            <a href="--><?php //echo $this->Url('administratorUser')?><!--">-->
<!--                                <i class="menu-icon fa fa-angle-double-right"></i>-->
<!--                                Danh sách-->
<!--                            </a>-->
<!--                        </li>-->
<!--                    --><?php //endif; ?>
<!--                </ul>-->
<!--            </li>-->
<!--        --><?php //endif; ?>
<!--        --><?php //if (IS_ADMIN || in_array('group', $per_controller)) : ?>
<!--            <li class="--><?php //if ($controller == 'group') : ?><!--active open--><?php //endif; ?><!--">-->
<!--                <a href="#" class="dropdown-toggle">-->
<!--                    <i class="menu-icon fa fa-group"></i>-->
<!--                    <span class="menu-text"> Nhóm </span>-->
<!--                    <b class="arrow fa fa-angle-down"></b>-->
<!--                </a>-->
<!--                <b class="arrow"></b>-->
<!--                <ul class="submenu">-->
<!--                    --><?php //if (IS_ADMIN || in_array('create', $per_controller_action['group'])): ?>
<!--                        <li --><?php //echo $controller == 'group' && $action == 'create' ? 'class="active"' : ''; ?><!-- >-->
<!--                            <a href="--><?php //echo $this->Url('administratorGroup', ['action'=>'create'])?><!--">-->
<!--                                <i class="menu-icon fa fa-angle-double-right"></i>-->
<!--                                Thêm nhóm-->
<!--                            </a>-->
<!--                            <b class="arrow"></b>-->
<!--                        </li>-->
<!--                    --><?php //endif; ?>
<!--                    --><?php //if (IS_ADMIN || in_array('index', $per_controller_action['group'])): ?>
<!--                        <li --><?php //echo $controller == 'group' && $action == 'index' ? 'class="active"' : ''; ?><!-- >-->
<!--                            <a href="--><?php //echo $this->Url('administratorGroup')?><!--">-->
<!--                                <i class="menu-icon fa fa-angle-double-right"></i>-->
<!--                                Danh sách-->
<!--                            </a>-->
<!--                        </li>-->
<!--                    --><?php //endif; ?>
<!--                </ul>-->
<!--            </li>-->
<!--        --><?php //endif; ?>
<!--        --><?php //if (IS_ADMIN || in_array('permission', $per_controller)) : ?>
<!--            <li class="--><?php //if ($controller == 'permission') : ?><!--active open--><?php //endif; ?><!--">-->
<!--                <a href="#" class="dropdown-toggle">-->
<!--                    <i class="menu-icon fa fa-lock"></i>-->
<!--                    <span class="menu-text"> Phân quyền </span>-->
<!--                    <b class="arrow fa fa-angle-down"></b>-->
<!--                </a>-->
<!--                <b class="arrow"></b>-->
<!--                <ul class="submenu">-->
<!--                    --><?php //if (IS_ADMIN || in_array('index', $per_controller_action['permission'])): ?>
<!--                        <li --><?php //echo $controller == 'permission' && $action == 'index' ? 'class="active"' : ''; ?><!-- >-->
<!--                            <a href="--><?php //echo $this->Url('administratorPermission')?><!--">-->
<!--                                <i class="menu-icon fa fa-angle-double-right"></i>-->
<!--                                Danh sách quyền-->
<!--                            </a>-->
<!--                        </li>-->
<!--                    --><?php //endif; ?>
<!--                </ul>-->
<!--            </li>-->
<!--        --><?php //endif; ?>
    </ul><!-- /.nav-list -->

    <div class="sidebar-toggle sidebar-collapse" id="sidebar-collapse">
        <i id="sidebar-toggle-icon" class="ace-save-state ace-icon fa fa-angle-double-left" data-icon1="ace-icon fa fa-angle-double-left" data-icon2="ace-icon fa fa-angle-double-right"></i>
    </div>
</div>