<div class="left">
    <div class="widget">
        <div class="widget-inner">
            <h3>Danh mục sản phẩm</h3>
            <div class="widget-border-top"></div>
            <div class="widget-content">
                <ul>
                    <li>
                        <a href="<?php echo SITE_URL; ?>the-loai/">Nội thất phong cách Hàn Quốc</a>
                        <ul class="sub-menu">
                            <li class="menu-item">
                                <a href="">Phòng ngủ đẹp Juliet -Eva</a>
                            </li>
                            <li class="menu-item">
                                <a href="">Nội thất tân cổ điển trắng</a>
                            </li>
                            <li class="menu-item">
                                <a href="">Giường da cao cấp</a>
                            </li>
                        </ul>
                    </li>
                    <li>
                        <a href="<?php echo SITE_URL; ?>the-loai/">Nội thất tân cổ điển trắng</a>
                    </li>
                    <li>
                        <a href="<?php echo SITE_URL; ?>the-loai/">Nội thất phong cách Hàn Quốc</a>
                    </li>
                    <li>
                        <a href="<?php echo SITE_URL; ?>the-loai/">Nội thất phong cách Hàn Quốc</a>
                        <ul class="sub-menu">
                            <li class="menu-item">
                                <a href="<?php echo SITE_URL; ?>the-loai/">Phòng ngủ đẹp Juliet -Eva</a>
                            </li>
                            <li class="menu-item">
                                <a href="<?php echo SITE_URL; ?>the-loai/">Nội thất tân cổ điển trắng</a>
                            </li>
                            <li class="menu-item">
                                <a href="<?php echo SITE_URL; ?>the-loai/">Giường da cao cấp</a>
                            </li>
                        </ul>
                    </li>
                    <li>
                        <a href="<?php echo SITE_URL; ?>the-loai/">Nội thất phong cách Hàn Quốc</a>
                        <ul class="sub-menu">
                            <li class="menu-item">
                                <a href="<?php echo SITE_URL; ?>the-loai/">Phòng ngủ đẹp Juliet -Eva</a>
                            </li>
                            <li class="menu-item">
                                <a href="<?php echo SITE_URL; ?>the-loai/">Nội thất tân cổ điển trắng</a>
                            </li>
                            <li class="menu-item">
                                <a href="<?php echo SITE_URL; ?>the-loai/">Giường da cao cấp</a>
                            </li>
                        </ul>
                    </li>
                </ul>
            </div>
        </div>
    </div>
    <div class="widget">
        <div class="widget-inner widget-info">
            <h3>Chuyên mục tư vấn</h3>
            <div class="widget-border-top"></div>
            <div class="widget-content">
                <ul>
                    <li>
                        <a>Các câu hỏi thường gặp</a>
                    </li>
                    <li>
                        <a>Chính sách đổi trả</a>
                    </li>
                    <li>
                        <a>Phương thức vận chuyển</a>
                    </li>
                    <li>
                        <a>Các câu hỏi thường gặp</a>
                    </li>
                    <li>
                        <a>Chính sách đổi trả</a>
                    </li>
                    <li>
                        <a>Phương thức vận chuyển</a>
                    </li>
                    <li>
                        <a>Các câu hỏi thường gặp</a>
                    </li>
                    <li>
                        <a>Chính sách đổi trả</a>
                    </li>
                    <li>
                        <a>Phương thức vận chuyển</a>
                    </li>
                </ul>
            </div>
        </div>
    </div>
</div>