<div class="footer">
    <div class="footer-top">
        <div class="footer-top-container">
            <div class="footer-top-text">
                <p>Megavita.vn - Sàn thương mại điện tử  hàng đầu Việt Nam</p>
                <p>Giấy phép số xx/GP-BC (Bộ VHTT) và xxx/GP-BBCVT (Bộ BCVT). Chịu trách nhiệm: Megavita.vn</p>
            </div>
            <div class="footer-register">
                <a>
                    <img src="<?php echo STATIC_URL; ?>images/gov.png">
                </a>
            </div>
        </div>
    </div>
	<div class="footer-contain">
		<div class="block-box">
			<div class="block-item">
				<div class="title">Công Ty TNHH Dược Phẩm MEGAVITA Việt Nam</div>
				<div class="text">
					<p><i class="icon24-code"></i>MST: 0312962299</p>
					<p><i class="icon24-mobile"></i>08 3602 7944</p>
					<p><i class="icon24-email"></i>center@megavita.vn</p>
					<p><i class="icon24-place"></i>46, Đường 3/2, Phường 12, Quận 10, TP.HCM (có chỗ đậu ô tô)</p>
				</div>
			</div>
            <div class="block-item">
                <div class="title">Về Megavita</div>
                <div class="text">
                    <ul>
                        <li><a>Hotline: 08 3602 7944</a></li>
                        <li><a>Email: center@megavita.vn</a></li>
                        <li><a>Các câu hỏi thường gặp</a></li>
                        <li><a>Chính sách đổi trả</a></li>
                        <li><a>Phương thức vận chuyển</a></li>
                        <li><a>Hướng dẫn đặt hàng</a></li>
                        <li><a>Hiểu đúng về thực phẩm chức năng.</a></li>
                    </ul>
                </div>
            </div>
            <div class="block-item">
                <div class="title">Dành cho quý khách</div>
                <div class="text">
                    <ul>
                        <li><a>Xem trạng thái đơn hàng</a></li>
                        <li><a>Lịch sử đơn hàng</a></li>
                        <li><a>Các câu hỏi thường gặp</a></li>
                        <li><a>Chính sách đổi trả</a></li>
                        <li><a>Phương thức vận chuyển</a></li>
                        <li><a>Hướng dẫn đặt hàng</a></li>
                        <li><a>Hiểu đúng về thực phẩm chức năng.</a></li>
                    </ul>
                </div>
            </div>
            <div class="block-item">
                <div class="title">Đăng ký nhận bản tin</div>
                <div class="text">Đăng ký nhận thông tin qua email để nhận được hàng triệu ưu đãi từ Megavita.vn</div>
            </div>
		</div>
	</div>
    <div class="footer-copyright">
        <div class="copyright-content">
            <div class="footer-copyright-text">Copyright © 2016 Megavita.vn</div>
        </div>
    </div>
</div>