<!DOCTYPE html>
<html lang="en">
<head>
    <title>Chiennn.me - I LOVE U</title>
    <meta name="description" content=""/>
    <meta name="viewport" content="width=device-width, initial-scale=1"/>
    <meta http-equiv="content-type" content="text/html; charset=UTF-8"/>
    <link href="<?php echo STATIC_URL; ?>/css/bootstrap/bootstrap.min.css" rel="stylesheet" type="text/css"/>
    <link href="<?php echo STATIC_URL; ?>/css/awesome/css/font-awesome.min.css" rel="stylesheet" type="text/css"/>
    <link href="<?php echo STATIC_URL; ?>/css/style.css" rel="stylesheet"/>
<!--    <script src="--><?php //echo STATIC_URL; ?><!--js/libs/jquery/jquery-2.2.4.min.js"></script>-->
<!--    <script type="application/javascript" src="--><?php //echo STATIC_URL; ?><!--js/main.js"></script>-->
<body>
<div class="wrapper">
    <div class="header">
    </div>
    <div class="clearfix"></div>
    <div class="main">
        <CENTER>
            <H1>WELCOME TO <a href="http://chiennn.me" style="cursor: pointer;">CHIENNN.ME</a></H1>
        </CENTER>
<!--        --><?php //echo $this->layout()->content; ?>
    </div>
    <div class="footer">
<!--        --><?php //echo $this->render('administrator/footer'); ?>
    </div>
</div>
</body>
</html>