<div class="rows" data-view="administrator/warehouse/create">
    <div class="col-xs-12">
        <div class="widget-body">
                <div class="widget-main">
                    <div id="fuelux-wizard-container" class="no-steps-container">
                        <div class="step-content pos-rel">
                            <div class="step-pane active" data-step="1">
                                <h3 class="lighter block green">Nhập thông tin nhập kho</h3>
                                <form class="form-horizontal" id="sample-form" method="post">
                                    <?php if(!empty($this->params['error'])):?>
                                        <div class="alert alert-danger">
                                            <button type="button" class="close" data-dismiss="alert">
                                                <i class="ace-icon fa fa-times"></i>
                                            </button>
                                            <strong>
                                                <i class="ace-icon fa fa-times"></i>
                                                Oh snap!
                                            </strong>
                                            <?php foreach ($this->params['messages'] as $ms):?>
                                            <p>- <?php echo $ms;?></p>
                                            <?php endforeach;?>
                                            <br>
                                        </div>
                                    <?php endif;?>
                                    <?php if(!empty($this->products['rows'])):?>
                                        <div class="form-group">
                                            <label for="inputError" class="col-xs-12 col-sm-3 col-md-3 control-label no-padding-right">Chọn thuốc muốn nhập</label>
                                            <div class="col-xs-12 col-sm-5">
                                            <span class="block input-icon input-icon-right">
                                                <select name="product_id" class="select-picker width-100" data-live-search="true">
                                                    <?php foreach($this->products['rows'] as $row):

                                                        $info = '<b>'.$row['product_name'] .'</b> -- Nhãn hiệu : '. $this->brands[$row['brand_id']]['brand_name'];
                                                        ?>
                                                        <option value="<?php echo $row['product_id'] ?>">
                                                            <?php echo $info;?>
                                                        </option>
                                                    <?php endforeach;?>
                                                </select>
                                            </span>
                                            </div>
                                        </div>
                                    <?php endif;?>
                                    <?php if(!empty($this->properties['rows'])):?>
                                        <div class="form-group">
                                            <label for="inputError" class="col-xs-12 col-sm-3 col-md-3 control-label no-padding-right">Chọn đơn vị tính</label>
                                            <div class="col-xs-12 col-sm-5">
                                            <span class="block input-icon input-icon-right">
                                                <select name="properties_id" class="select-picker width-100" data-live-search="true">
                                                    <?php foreach($this->properties['rows'] as $row):?>
                                                        <option value="<?php echo $row['id']?>">
                                                            <?php echo $row['properties_name']?>
                                                        </option>
                                                    <?php endforeach;?>
                                                </select>
                                            </span>
                                            </div>
                                        </div>
                                    <?php endif;?>
                                    <div class="form-group">
                                        <label for="inputWarning" class="col-xs-12 col-sm-3 control-label no-padding-right">Ngày sản xuất <span class="red"> (*)</span></label>
                                        <div class="col-xs-12 col-sm-5">
                                            <span class="block input-icon input-icon-right">
                                                <input class="width-100 datetimepicker" type="text" name="nsx" value="<?php echo empty($this->params['nsx']) ? date('d/m/Y') : $this->params['nsx']?>">
                                            </span>
                                        </div>
                                    </div>

                                    <div class="form-group">
                                        <label for="inputWarning" class="col-xs-12 col-sm-3 control-label no-padding-right">Hạn sử dụng <span class="red"> (*)</span></label>
                                        <div class="col-xs-12 col-sm-5">
                                            <span class="block input-icon input-icon-right">
                                                <input class="width-100 datetimepicker" type="text" name="hsd" value="<?php echo empty($this->params['hsd']) ? date('d/m/Y') : $this->params['hsd']?>">
                                            </span>
                                        </div>
                                    </div>

                                    <div class="form-group">
                                        <label for="inputWarning" class="col-xs-12 col-sm-3 control-label no-padding-right">Số lô sản xuất <span class="red"> (*)</span></label>
                                        <div class="col-xs-12 col-sm-5">
                                            <span class="block input-icon input-icon-right">
                                                <input placeholder="Nhập số lô sản xuất" class="width-100" type="text" name="production_batch" value="<?php echo empty($this->params['production_batch']) ? '' : $this->params['production_batch']?>">
                                            </span>
                                        </div>
                                    </div>

                                    <div class="form-group">
                                        <label for="inputWarning" class="col-xs-12 col-sm-3 control-label no-padding-right">Bật thông báo sắp hết hạn sử dụng trước bao nhiêu ngày <span class="red"> (*)</span></label>
                                        <div class="col-xs-12 col-sm-5">
                                            <span class="block input-icon input-icon-right">
                                                <input placeholder="Bật thông báo sắp hết hạn sử dụng trước bao nhiêu ngày" class="width-100 price-mask" type="text" name="flag_notify" value="<?php echo empty($this->params['flag_notify']) ? 150 : $this->params['flag_notify']?>">
                                            </span>
                                        </div>
                                    </div>

                                    <div class="form-group">
                                        <label for="inputWarning" class="col-xs-12 col-sm-3 control-label no-padding-right">Số lượng <span class="red"> (*)</span></label>
                                        <div class="col-xs-12 col-sm-5">
                                            <span class="block input-icon input-icon-right">
                                                <input placeholder="Nhập số lượng" class="width-100 price-mask" type="text" name="quantity" value="<?php echo !empty($this->params['quantity']) ? $this->params['quantity'] : ''?>">
                                            </span>
                                        </div>
                                    </div>

                                    <div class="form-group">
                                        <label for="inputWarning" class="col-xs-12 col-sm-3 control-label no-padding-right">Giá mua vào trên mỗi đơn vị (VNĐ)<span class="red"> (*)</span></label>
                                        <div class="col-xs-12 col-sm-5">
                                            <span class="block input-icon input-icon-right">
                                                <input class="width-100 price-mask" type="text" name="unit_price" value="<?php echo !empty($this->params['unit_price']) ? $this->params['unit_price'] : ''?>">
                                            </span>
                                        </div>
                                    </div>

                                    <div class="form-group">
                                        <label for="inputWarning" class="col-xs-12 col-sm-3 control-label no-padding-right">Chiết khấu % (nếu có)</label>
                                        <div class="col-xs-12 col-sm-5">
                                            <span class="block input-icon input-icon-right">
                                                <input class="width-100 price-mask" type="text" name="discount" maxlength="3" value="<?php echo !empty($this->params['discount']) ? $this->params['discount'] : ''?>">
                                            </span>
                                        </div>
                                    </div>

                                    <div class="form-group">
                                        <label for="inputWarning" class="col-xs-12 col-sm-3 control-label no-padding-right">Tổng tiền phải trả VNĐ<span class="red"> (*)</span></label>
                                        <div class="col-xs-12 col-sm-5">
                                            <span class="block input-icon input-icon-right">
                                                <input class="width-100 price-mask" type="text" readonly name="total_price" value="<?php echo !empty($this->params['total_price']) ? $this->params['total_price'] : ''?>">
                                            </span>
                                        </div>
                                    </div>

                                    <div class="form-group">
                                        <label for="inputWarning" class="col-xs-12 col-sm-3 control-label no-padding-right">Ghi chú thêm</label>
                                        <div class="col-xs-12 col-sm-7">
                                            <span class="block input-icon input-icon-right">
                                                <textarea name="note" class="ckeditor" rows="3" cols="20" name="editor"><?php
                                                    echo !empty($this->params['note']) ? $this->params['note'] : '' ?></textarea>
                                            </span>
                                        </div>
                                    </div>

                                    <hr>
                                    <div class="center">
                                        <button class="btn btn-success" type="submit">
                                            <i class="ace-icon fa fa-save"></i>
                                            Nhập kho
                                        </button>
                                    </div>
                                </form>
                            </div>
                        </div>
                    </div
                </div><!-- /.widget-main -->
            </div><!-- /.widget-body -->
    </div>
</div>