<div data-view="administrator/warehouse/expire">
    <div class="col-xs-12">
        <form method="get" class="form-search">
            <div class="col-xs-12" style="margin-bottom: 10px">
                <div class="col-xs-6">
                    <a class="btn btn-xs btn-danger remove-all" href="javascript:;" style="margin-right: 5px">
                        <i class="fa fa-trash "></i> Xóa
                    </a>
                    <a class="btn btn-xs btn-success" href="<?php echo $this->Url('administratorProduct', ['action'=>'create'])?>">
                        <i class="ace-icon fa fa-plus">
                            Thêm
                        </i>
                    </a>
                </div>
                <div class="col-xs-4 col-xs-offset-2">
                    <span class="input-icon">
                        <input type="text" name="search" placeholder="Tìm kiếm ..." class="nav-search-input" autocomplete="off"
                               value="<?php echo (empty($this->params['search'])) ? '' : $this->params['search'];?>"
                        >
                    </span>
                    <button type="submit" class="btn btn-xs btn-primary">
                        <i class="ace-icon fa fa-search"></i> Tìm
                    </button>
                </div>
            </div>
        <table id="simple-table" class="table  table-bordered table-hover">
            <thead>
            <tr>
                <th class="center"><span class="fa fa-list-alt"></span> Tên thuốc</th>
                <th class="center"><span class="fa fa-barcode"></span> Đơn vị tính </th>
                <th class="center"> Số lượng hết hạn</th>
                <th class="center"><span class="fa fa-calendar"></span> Ngày nhập</th>
                <th class="center"><span class="fa fa-calendar"></span> NSX</th>
                <th class="center"><span class="fa fa-calendar"></span> HSD</th>
                <th class="center"><span class="fa fa-barcode"></span> Số lô</th>
            </tr>
            </thead>
            <tbody>
            <?php if(!empty($this->warehouses)):
                foreach ($this->warehouses['rows'] as $row):?>
                    <tr>
                        <td><a><b><?php echo !empty($this->products[$row['product_id']]) ? $this->products[$row['product_id']]['product_name'] : ''?></b></a></td>
                        <td class="center"><b><?php echo !empty($this->properties[$row['properties_id']]) ? $this->properties[$row['properties_id']]['properties_name'] : ''?></b></td>
                        <td class="center"><?php echo number_format($row['stock']);?></td>
                        <td class="center"><b class="red"><?php echo date('d-m-Y',$row['created_date']);?></b></td>
                        <td class="center"><?php echo date('d-m-Y',$row['nsx']);?></td>
                        <td class="center"><b class="red"><?php echo date('d-m-Y',$row['hsd']);?></b></td>
                        <td class="center"><?php echo empty($row['production_batch']) ? '' : $row['production_batch'];?></td>
                    </tr>
                <?php endforeach; endif;?>
            </tbody>
        </table>
        <?php
        $params = $this->params;
        $params['controller'] = $params['strController'];
        $paging = $this->pagingText($params);
        if(!empty($paging)){
            echo $paging;
        }
        ?>
        </form>
    </div>
</div>