<div class="rows" data-view="administrator/warehouse/index">
    <div class="col-xs-12">
        <form method="get" class="form-search">
            <div class="col-xs-12" style="margin-bottom: 10px">
                <div class="col-xs-6">
                    <a class="btn btn-xs btn-danger remove-all" href="javascript:;" style="margin-right: 5px">
                        <i class="fa fa-trash "></i> Xóa
                    </a>
                    <a class="btn btn-xs btn-success" href="<?php echo $this->Url('administratorWarehouse', ['action'=>'create'])?>">
                        <i class="ace-icon fa fa-plus">
                            Thêm
                        </i>
                    </a>
                </div>
                <div class="col-xs-4 col-xs-offset-2">
                    <span class="input-icon">
                        <input type="text" name="search" placeholder="Tìm kiếm ..." class="nav-search-input" autocomplete="off"
                               value="<?php echo (empty($this->params['search'])) ? '' : $this->params['search'];?>"
                        >
                    </span>
                    <button type="submit" class="btn btn-xs btn-primary">
                        <i class="ace-icon fa fa-search"></i> Tìm
                    </button>
                </div>
            </div>
        <table id="simple-table" class="table  table-bordered table-hover">
            <thead>
            <tr>
                <th class="center"> # </th>
                <th class="center"><span class="fa fa-list-alt"></span> Tên thuốc</th>
                <th class="center"><span class="fa fa-cc-mastercard"></span> Hãng sản xuất</th>
                <th class="center"><span class="fa fa-barcode"></span> ĐVT </th>
                <th class="center"> SL</th>
                <th class="center"> Đơn giá (vnđ)</th>
                <th class="center"> CK (%)</th>
                <th class="center"> Tổng tiền (vnđ)</th>
                <th class="center"><span class="fa fa-calendar"></span> Ngày nhập</th>
<!--                <th class="center"><span class="fa fa-user"></span>Người nhập</th>-->
                <th class="center"><span class="fa fa-calendar"></span> NSX</th>
                <th class="center"><span class="fa fa-calendar"></span> HSD</th>
                <th class="center"><span class="fa fa-barcode"></span> Số lô</th>
                <th class="center"><span class="fa fa-spin"></span> Thông báo</th>
                <th class="center"><span class="fa icon-gears"></span> Tùy chỉnh</th>
            </tr>
            </thead>
            <tbody>
            <?php if(!empty($this->warehouses)):
                foreach ($this->warehouses['rows'] as $row):
                    $flag_notify = $row['flag_notify'];
                    $is_notify = empty($row['is_notify']) ? 0 : $row['is_notify'];
                    $is_bell = false;
                    $icon = '';
                    if($row['hsd'] > time() && $row['hsd'] - time() <= $flag_notify * 60*60*24 && $is_notify){
                        $is_bell = true;
                        $icon = 'ace-icon fa fa-bell bigger-120';
                    }elseif($row['hsd'] < time()){
                        $icon = 'ace-icon fa fa-bell-slash-o bigger-120';
                    }
                    $brand_id = empty($this->products[$row['product_id']]['brand_id']) ? 0 : $this->products[$row['product_id']]['brand_id'];
                    ?>
                    <tr <?php if($is_bell):?>class="label-yellow"<?php endif;?>>
                        <td class="center"><input type="checkbox" name="data-id" class="input" value="<?php echo $row['warehouse_id']?>"></td>
                        <td><a href="javascript:;"><b><?php echo !empty($this->products[$row['product_id']]) ? $this->products[$row['product_id']]['product_name'] : ''?></b></a></td>
                        <td><a href="javascript:;"><b><?php echo empty($this->brands[$brand_id]) ? '' : $this->brands[$brand_id]['brand_name']?></b></a></td>
                        <td class="center"><b><?php echo !empty($this->properties[$row['properties_id']]) ? $this->properties[$row['properties_id']]['properties_name'] : ''?></b></td>
                        <td class="text-right"><?php echo number_format($row['quantity']);?></td>
                        <td class="text-right"><?php echo empty($row['unit_price']) ? 0 : number_format($row['unit_price']);?></td>
                        <td class="text-right"><?php echo empty($row['discount']) ? 0 : $row['discount'];?></td>
                        <td class="text-right"><?php echo empty($row['total_price']) ? 0 : number_format($row['total_price']);?></td>
                        <td class="center"><b class="red"><?php echo date('d-m-Y',$row['created_date']);?></b></td>
<!--                        <td class="center">--><?php //echo !empty($this->users[$row['user_created']]) ? $this->users[$row['user_created']]['full_name'] : ''?><!--</td>-->
                        <td class="center"><?php echo date('d-m-Y',$row['nsx']);?></td>
                        <td class="center"><b class="red"><?php echo date('d-m-Y',$row['hsd']);?></b></td>
                        <td class="center"><?php echo empty($row['production_batch']) ? '' : $row['production_batch'];?></td>
                        <td class="text-right"><?php echo $row['flag_notify'];?></td>
                        <td class="center">
                            <div class="hidden-sm hidden-xs btn-group">
                                <?php if($is_bell):?>
                                <a class="btn btn-xs btn-warning" data-toggle="tooltip" title="Thuốc sắp hết hạn">
                                    <i class="<?php echo $icon?>"></i>
                                </a>
                                <?php elseif (!empty($icon)):;?>
                                <a class="btn btn-xs btn-danger" data-toggle="tooltip" title="Thuốc đã hết hạn">
                                    <i class="ace-icon fa fa-bell-slash-o bigger-120"></i>
                                </a>
                                <?php endif;?>
                                <a class="btn btn-xs btn-info" data-toggle="tooltip" title="Cập nhật" href="<?php echo $this->Url('administratorWarehouse', ['action'=>'edit', 'id' =>$row['warehouse_id']])?>">
                                    <i class="ace-icon fa fa-pencil bigger-120"></i>
                                </a>
                            </div>
                        </td>
                    </tr>
                <?php endforeach; endif;?>
            </tbody>
        </table>
        <?php
        $params = $this->params;
        $params['controller'] = $params['strController'];
        $paging = $this->pagingText($params);
        if(!empty($paging)){
            echo $paging;
        }
        ?>
        </form>
    </div>
</div>