<div data-view="administrator/warehouse/index">
    <div class="col-item">
        <form method="get">
            <div class="rows" style="border-bottom: none; border-top: 1px solid #ddd">
                <div class="search-product">
                    <div class="col-lg-2 pull-left" style="margin-top: 25px">
                        <div id="editable-sample_length" class="dataTables_length no-padding">
                            <a class="btn btn-success" href="<?php echo $this->Url('administratorWarehouse', ['action'=>'create'])?>"><i class="icon-plus-sign-alt"></i> Thêm</a>
                            <a class="btn btn-danger remove-all" href="javascript:;"><i class="icon-trash "></i> Xóa</a>
                        </div>
                    </div>
                    <div class="search-title">
                        <div class="search-title-block">
                            <input class="search-product-title" type="text" name="search" placeholder="Tìm kiếm theo tên" value="<?php echo !empty($this->params['search']) ? $this->params['search'] : ''?>" placeholder="Tìm kiếm theo tên">
                            <button class="search-products" type="submit">
                                <i class="icon-search"></i>
                            </button>
                        </div>
                    </div>
                </div>
            </div>
            <table style="margin-bottom: 0" class="table table-striped table-bordered table-hover">
                <thead>
                <tr>
                    <th class="center"> # </th>
                    <th class="center"><span class="icon icon-list-alt"></span> Tên thuốc</th>
                    <th class="center"><span class="icon icon-barcode"></span> Đơn vị tính </th>
                    <th class="center">Số lượng</th>
                    <th class="center"><span class="icon icon-calendar"></span> Ngày nhập</th>
                    <th class="center"><span class="icon icon-user"></span>Người nhập</th>
                    <th class="center"><span class="icon icon-calendar"></span> NSX</th>
                    <th class="center"><span class="icon icon-calendar"></span> HSD</th>
                    <th class="center"><span class="icon icon-barcode"></span> Số lô SX</th>
                    <th class="center"><span class="icon icon-spin"></span> Thông báo</th>
                    <th class="center"><span class="icon icon-gears"></span> Tùy chỉnh</th>
                </tr>
                </thead>
                <tbody>
                <?php if(!empty($this->warehouses)):
                    foreach ($this->warehouses['rows'] as $row):
                        $flag_notify = $row['flag_notify'];
                        $is_notify = empty($row['is_notify']) ? 0 : $row['is_notify'];
                        $is_bell = false;
                        if($row['hsd'] - time() <= $flag_notify * 60*60*24 && $is_notify){
                            $is_bell = true;
                        }
                    ?>
                    <tr>
                        <td class="center"><input type="checkbox" name="data-id" class="input" value="<?php echo $row['warehouse_id']?>"></td>
                        <td><a><b><?php echo !empty($this->products[$row['product_id']]) ? $this->products[$row['product_id']]['product_name'] : ''?></b></a></td>
                        <td class="center"><b><?php echo !empty($this->properties[$row['properties_id']]) ? $this->properties[$row['properties_id']]['properties_name'] : ''?></b></td>
                        <td class="center"><?php echo $row['quantity'];?></td>
                        <td class="center"><b class="red"><?php echo date('d-m-Y',$row['created_date']);?></b></td>
                        <td class="center"><?php echo !empty($this->users[$row['user_created']]) ? $this->users[$row['user_created']]['full_name'] : ''?></td>
                        <td class="center"><?php echo date('d-m-Y',$row['nsx']);?></td>
                        <td class="center"><b class="red"><?php echo date('d-m-Y',$row['hsd']);?></b></td>
                        <td class="center"><?php echo empty($row['production_batch']) ? '' : $row['production_batch'];?></td>
                        <td class="center"><?php echo $row['flag_notify'];?></td>
                        <td class="center">
                            <?php if($is_bell):?>
                            <a data-toggle="tooltip" title="Thuốc sắp hết hạn" class="btn btn-small btn-primary">
                                <i class="icon icon-bell-alt"></i>
                            </a>
                            <?php endif;?>
                            <a data-toggle="tooltip" title="Cập nhật" class="btn btn-small btn-primary" href="<?php echo $this->Url('administratorWarehouse', ['action'=>'edit', 'id' => $row['warehouse_id']])?>">
                                <i class="icon icon-edit"></i>
                            </a>
                        </td>
                    </tr>
                <?php endforeach; endif;?>
                </tbody>
            </table>
        </form>
    </div>
</div>