<div class="data-view" data-view="administrator/menu/edit">
    <div class="cat-content">
        <form name="form" class="form" method="post">
            <div class="col-cate-left" style="margin-bottom: 40px">
                <?php if(!empty($this->params['error'])):?>
                    <h4 class="header red lighter bigger" style="margin-top: -15px; margin-bottom: 30px">
                        <center>--------<b>ERROR</b>----------</br></center>
                        <center><?php echo $this->params['error']?></center>
                    </h4>
                <?php endif;?>

                <span class="block input-icon input-icon-right">
                    <label>Tên Menu <span class="red">(*)</span></label>
                    <input name="menu_name" type="text" class="span12" placeholder="Nhập tên menu" required
                           value="<?php echo empty($this->params['menu_name']) ? $this->menu['menu_name'] : $this->params['menu_name'];?>"
                    >
                </span>

                <span class="block input-icon input-icon-right">
                    <label>URL <span class="red">(*)</span></label>
                    <input name="url" type="text" class="span12" placeholder="Nhập URL" required
                           value="<?php echo empty($this->params['url']) ? $this->menu['url'] : $this->params['url'];?>"
                    >
                </span>

                <span class="block input-icon input-icon-right">
                    <label>Menu cha</label>
                    <select class="span12" name="parent_id">
                        <option value="0">
                            Chọn menu
                        </option>
                        <?php if (!empty($this->parent['rows'])):
                            foreach ($this->parent['rows'] as $row):
                                ?>
                                <option value="<?php echo $row['menu_id'];?>" <?php echo empty($this->params['parent_id']) ? ($this->menu['parent_id'] == $row['menu_id'] ? 'selected' : '') : ($this->params['parent_id'] == $row['menu_id'] ? 'selected' : '')?>>
                                    <a href="javascript:;"><b><?php echo $row['menu_name']; ?></b></a>
                                </option>
                            <?php endforeach;
                        endif;
                        ?>
                    </select>
                </span>

                <span class="block input-icon input-icon-right">
                    <label>Độ ưu tiên <span class="red">(*)</span></label>
                    <input name="sort" type="text" class="span12" placeholder="" required
                        value="<?php echo !isset($this->params['sort']) ? (empty($this->menu['sort']) ? '' : $this->menu['sort']) : $this->params['sort'];?>"
                    >
                </span>

                <span class="block input-icon input-icon-right">
                    <label>Trạng thái</label>
                    <select class="span12" name="status">
                        <?php foreach ($this->render_status as $id => $name):?>
                            <option value="<?php echo $id;?>" <?php echo isset($this->params['status']) && $this->params['status'] == $id ? 'selected' : ($this->menu['status'] == $id ? 'selected' : '')?>>
                                <?php echo $name?>
                            </option>
                        <?php endforeach;?>
                    </select>
                </span>

                <span class="block input-icon input-icon-right" style="margin-top: 10px">
                    <button class="btn btn-success" name="save"><i class="icon icon-save"></i> Lưu</button>
                    <button class="btn btn-danger" name="save_quit"><i class="icon icon-save"></i> Lưu & Thoát</button>
                </span>
            </div>
        </form>
    </div>
</div>