<div class="block-box">
	<div class="block-content">
		<div class="left">
			<div class="widget">
				<div class="widget-inner">
					<h3>Danh mục sản phẩm</h3>
					<div class="widget-border-top"></div>
					<div class="widget-content">
						<ul>
							<li class="active">
								<a href="<?php echo SITE_URL; ?>the-loai/">Nội thất phòng ngủ</a>
								<ul class="sub-menu">
									<li class="menu-item">
										<a href="">Phòng ngủ đẹp Juliet -Eva</a>
									</li>
									<li class="menu-item">
										<a href="">Nội thất tân cổ điển trắng</a>
									</li>
									<li class="menu-item">
										<a href="">Giường da cao cấp</a>
									</li>
								</ul>
							</li>
							<li>
								<a>Nội thất phong cách Hàn Quốc</a>
							</li>
							<li>
								<a>Nội thất tân cổ điển trắng</a>
							</li>
							<li>
								<a>Nội thất phong cách Hàn Quốc</a>
							</li>
							<li>
								<a>Nội thất tân cổ điển trắng</a>
							</li>
							<li>
								<a>Nội thất phong cách Hàn Quốc</a>
							</li>
						</ul>
					</div>
				</div>
			</div>
			<div class="widget">
				<div class="widget-inner widget-info">
					<h3>Chuyên mục tư vấn</h3>
					<div class="widget-border-top"></div>
					<div class="widget-content">
						<ul>
							<li>
								<a>Các câu hỏi thường gặp</a>
							</li>
							<li>
								<a>Chính sách đổi trả</a>
							</li>
							<li>
								<a>Phương thức vận chuyển</a>
							</li>
							<li>
								<a>Các câu hỏi thường gặp</a>
							</li>
							<li>
								<a>Chính sách đổi trả</a>
							</li>
							<li>
								<a>Phương thức vận chuyển</a>
							</li>
							<li>
								<a>Các câu hỏi thường gặp</a>
							</li>
							<li>
								<a>Chính sách đổi trả</a>
							</li>
							<li>
								<a>Phương thức vận chuyển</a>
							</li>
						</ul>
					</div>
				</div>
			</div>
			<div class="widget-news">
				<div class="box-head">THÔNG TIN CẦN BIẾT</div>
				<div class="box-content">
					<ul>
						<li>
							<div class="img">
								<img src="http://static.megavita.vn/uploads/content/2017/03/01/thumbs/116x116_1488334000.1886.jpg">
							</div>
							<div class="detail">
								<div class="title">
									<a>Top 5 cách chống lão hoá da mặt cho tuổi 30</a>
								</div>
								<div class="time">
									<div class="date">28/02/2017</div>
								</div>
							</div>
						</li>
						<li>
							<div class="img">
								<img src="http://static.megavita.vn/uploads/content/2017/03/01/thumbs/116x116_1488334000.1886.jpg">
							</div>
							<div class="detail">
								<div class="title">
									<a>Top 5 cách chống lão hoá da mặt cho tuổi 30</a>
								</div>
								<div class="time">
									<div class="date">28/02/2017</div>
								</div>
							</div>
						</li>
						<li>
							<div class="img">
								<img src="http://static.megavita.vn/uploads/content/2017/03/01/thumbs/116x116_1488334000.1886.jpg">
							</div>
							<div class="detail">
								<div class="title">
									<a>Top 5 cách chống lão hoá da mặt cho tuổi 30</a>
								</div>
								<div class="time">
									<div class="date">28/02/2017</div>
								</div>
							</div>
						</li>
						<li>
							<div class="img">
								<img src="http://static.megavita.vn/uploads/content/2017/03/01/thumbs/116x116_1488334000.1886.jpg">
							</div>
							<div class="detail">
								<div class="title">
									<a>Top 5 cách chống lão hoá da mặt cho tuổi 30</a>
								</div>
								<div class="time">
									<div class="date">28/02/2017</div>
								</div>
							</div>
						</li>
					</ul>
				</div>
			</div>
		</div>
		<div class="main border-left">
			<div class="main-title">
				<h3>Nội thất phòng ngủ</h3>
			</div>
			<div class="list-items margin-top-15">
				<div class="item">
					<div class="item-view">
						<ul class="item-fluid">
							<li class="img">
								<div class="thumbnails">
									<a href="/san-pham/bo-phong-ngu-cao-cap-703/" class="thumbnail">
										<img src="https://www.kymdan.com/attachment.do?file=attachment/49/SYMMETRIC_avatar_384x230_384x288.jpg" title="Bộ phòng ngủ cao cấp 703" alt="Bộ phòng ngủ cao cấp 703">
									</a>
								</div>
							</li>
							<li>
								<h2 class="entry-title">
									<a title="Bộ phòng ngủ cao cấp 703" href="/san-pham/bo-phong-ngu-cao-cap-703/">Bộ phòng ngủ cao cấp 703</a>
								</h2>
							</li>
							<li class="price-sale"> 122,000,000 vnđ</li>
							<li class="price-old"> 125,000,000 vnd</li>
							<li>
								<a style="display:block;line-height:15px;color:#ffffff" rel="nofollow" href="/san-pham/bo-phong-ngu-cao-cap-703/" class="text-right mybutton">
									<i class="fa fa-shopping-cart" aria-hidden="true"></i> Đặt mua
								</a>
							</li>
						</ul>
					</div>
				</div>
				<div class="item">
					<div class="item-view">
						<ul class="item-fluid">
							<li class="img">
								<div class="thumbnails">
									<a href="/san-pham/bo-phong-ngu-cao-cap-703/" class="thumbnail">
										<img src="https://www.kymdan.com/attachment.do?file=attachment/44/bed_light_new(l)_384x288.jpg" title="Bộ phòng ngủ cao cấp 703" alt="Bộ phòng ngủ cao cấp 703">
									</a>
								</div>
							</li>
							<li>
								<h2 class="entry-title">
									<a title="Bộ phòng ngủ cao cấp 703" href="/san-pham/bo-phong-ngu-cao-cap-703/">Bộ phòng ngủ cao cấp 703</a>
								</h2>
							</li>
							<li class="price-sale"> 122,000,000 vnđ</li>
							<li class="price-old"> 125,000,000 vnd</li>
							<li>
								<a style="display:block;line-height:15px;color:#ffffff" rel="nofollow" href="/san-pham/bo-phong-ngu-cao-cap-703/" class="text-right mybutton">
									<i class="fa fa-shopping-cart" aria-hidden="true"></i> Đặt mua
								</a>
							</li>
						</ul>
					</div>
				</div>
				<div class="item">
					<div class="item-view">
						<ul class="item-fluid">
							<li class="img">
								<div class="thumbnails">
									<a href="/san-pham/bo-phong-ngu-cao-cap-703/" class="thumbnail">
										<img src="https://www.kymdan.com/attachment.do?file=attachment/6309/DIAMOND_avatar_384x288.jpg" title="Bộ phòng ngủ cao cấp 703" alt="Bộ phòng ngủ cao cấp 703">
									</a>
								</div>
							</li>
							<li>
								<h2 class="entry-title">
									<a title="Bộ phòng ngủ cao cấp 703" href="/san-pham/bo-phong-ngu-cao-cap-703/">Bộ phòng ngủ cao cấp 703</a>
								</h2>
							</li>
							<li class="price-sale"> 122,000,000 vnđ</li>
							<li class="price-old"> 125,000,000 vnd</li>
							<li>
								<a style="display:block;line-height:15px;color:#ffffff" rel="nofollow" href="/san-pham/bo-phong-ngu-cao-cap-703/" class="text-right mybutton">
									<i class="fa fa-shopping-cart" aria-hidden="true"></i> Đặt mua
								</a>
							</li>
						</ul>
					</div>
				</div>
				<div class="item">
					<div class="item-view">
						<ul class="item-fluid">
							<li class="img">
								<div class="thumbnails">
									<a href="/san-pham/bo-phong-ngu-cao-cap-703/" class="thumbnail">
										<img src="https://www.kymdan.com/attachment.do?file=attachment/500/bed_rainbow(l)_384x288.jpg" title="Bộ phòng ngủ cao cấp 703" alt="Bộ phòng ngủ cao cấp 703">
									</a>
								</div>
							</li>
							<li>
								<h2 class="entry-title">
									<a title="Bộ phòng ngủ cao cấp 703" href="/san-pham/bo-phong-ngu-cao-cap-703/">Bộ phòng ngủ cao cấp 703</a>
								</h2>
							</li>
							<li class="price-sale"> 122,000,000 vnđ</li>
							<li class="price-old"> 125,000,000 vnd</li>
							<li>
								<a style="display:block;line-height:15px;color:#ffffff" rel="nofollow" href="/san-pham/bo-phong-ngu-cao-cap-703/" class="text-right mybutton">
									<i class="fa fa-shopping-cart" aria-hidden="true"></i> Đặt mua
								</a>
							</li>
						</ul>
					</div>
				</div>
				<div class="item">
					<div class="item-view">
						<ul class="item-fluid">
							<li class="img">
								<div class="thumbnails">
									<a href="/san-pham/bo-phong-ngu-cao-cap-703/" class="thumbnail">
										<img src="https://www.kymdan.com/attachment.do?file=attachment/49/SYMMETRIC_avatar_384x230_384x288.jpg" title="Bộ phòng ngủ cao cấp 703" alt="Bộ phòng ngủ cao cấp 703">
									</a>
								</div>
							</li>
							<li>
								<h2 class="entry-title">
									<a title="Bộ phòng ngủ cao cấp 703" href="/san-pham/bo-phong-ngu-cao-cap-703/">Bộ phòng ngủ cao cấp 703</a>
								</h2>
							</li>
							<li class="price-sale"> 122,000,000 vnđ</li>
							<li class="price-old"> 125,000,000 vnd</li>
							<li>
								<a style="display:block;line-height:15px;color:#ffffff" rel="nofollow" href="/san-pham/bo-phong-ngu-cao-cap-703/" class="text-right mybutton">
									<i class="fa fa-shopping-cart" aria-hidden="true"></i> Đặt mua
								</a>
							</li>
						</ul>
					</div>
				</div>
				<div class="item">
					<div class="item-view">
						<ul class="item-fluid">
							<li class="img">
								<div class="thumbnails">
									<a href="/san-pham/bo-phong-ngu-cao-cap-703/" class="thumbnail">
										<img src="https://www.kymdan.com/attachment.do?file=attachment/6368/RULER_avatar_384x288.jpg" title="Bộ phòng ngủ cao cấp 703" alt="Bộ phòng ngủ cao cấp 703">
									</a>
								</div>
							</li>
							<li>
								<h2 class="entry-title">
									<a title="Bộ phòng ngủ cao cấp 703" href="/san-pham/bo-phong-ngu-cao-cap-703/">Bộ phòng ngủ cao cấp 703</a>
								</h2>
							</li>
							<li class="price-sale"> 122,000,000 vnđ</li>
							<li class="price-old"> 125,000,000 vnd</li>
							<li>
								<a style="display:block;line-height:15px;color:#ffffff" rel="nofollow" href="/san-pham/bo-phong-ngu-cao-cap-703/" class="text-right mybutton">
									<i class="fa fa-shopping-cart" aria-hidden="true"></i> Đặt mua
								</a>
							</li>
						</ul>
					</div>
				</div>
				<div class="item">
					<div class="item-view">
						<ul class="item-fluid">
							<li class="img">
								<div class="thumbnails">
									<a href="/san-pham/bo-phong-ngu-cao-cap-703/" class="thumbnail">
										<img src="https://www.kymdan.com/attachment.do?file=attachment/500/bed_rainbow(l)_384x288.jpg" title="Bộ phòng ngủ cao cấp 703" alt="Bộ phòng ngủ cao cấp 703">
									</a>
								</div>
							</li>
							<li>
								<h2 class="entry-title">
									<a title="Bộ phòng ngủ cao cấp 703" href="/san-pham/bo-phong-ngu-cao-cap-703/">Bộ phòng ngủ cao cấp 703</a>
								</h2>
							</li>
							<li class="price-sale"> 122,000,000 vnđ</li>
							<li class="price-old"> 125,000,000 vnd</li>
							<li>
								<a style="display:block;line-height:15px;color:#ffffff" rel="nofollow" href="/san-pham/bo-phong-ngu-cao-cap-703/" class="text-right mybutton">
									<i class="fa fa-shopping-cart" aria-hidden="true"></i> Đặt mua
								</a>
							</li>
						</ul>
					</div>
				</div>
				<div class="item">
					<div class="item-view">
						<ul class="item-fluid">
							<li class="img">
								<div class="thumbnails">
									<a href="/san-pham/bo-phong-ngu-cao-cap-703/" class="thumbnail">
										<img src="https://www.kymdan.com/attachment.do?file=attachment/500/bed_rainbow(l)_384x288.jpg" title="Bộ phòng ngủ cao cấp 703" alt="Bộ phòng ngủ cao cấp 703">
									</a>
								</div>
							</li>
							<li>
								<h2 class="entry-title">
									<a title="Bộ phòng ngủ cao cấp 703" href="/san-pham/bo-phong-ngu-cao-cap-703/">Bộ phòng ngủ cao cấp 703</a>
								</h2>
							</li>
							<li class="price-sale"> 122,000,000 vnđ</li>
							<li class="price-old"> 125,000,000 vnd</li>
							<li>
								<a style="display:block;line-height:15px;color:#ffffff" rel="nofollow" href="/san-pham/bo-phong-ngu-cao-cap-703/" class="text-right mybutton">
									<i class="fa fa-shopping-cart" aria-hidden="true"></i> Đặt mua
								</a>
							</li>
						</ul>
					</div>
				</div>
				<div class="item">
					<div class="item-view">
						<ul class="item-fluid">
							<li class="img">
								<div class="thumbnails">
									<a href="/san-pham/bo-phong-ngu-cao-cap-703/" class="thumbnail">
										<img src="https://www.kymdan.com/attachment.do?file=attachment/6368/RULER_avatar_384x288.jpg" title="Bộ phòng ngủ cao cấp 703" alt="Bộ phòng ngủ cao cấp 703">
									</a>
								</div>
							</li>
							<li>
								<h2 class="entry-title">
									<a title="Bộ phòng ngủ cao cấp 703" href="/san-pham/bo-phong-ngu-cao-cap-703/">Bộ phòng ngủ cao cấp 703</a>
								</h2>
							</li>
							<li class="price-sale"> 122,000,000 vnđ</li>
							<li class="price-old"> 125,000,000 vnd</li>
							<li>
								<a style="display:block;line-height:15px;color:#ffffff" rel="nofollow" href="/san-pham/bo-phong-ngu-cao-cap-703/" class="text-right mybutton">
									<i class="fa fa-shopping-cart" aria-hidden="true"></i> Đặt mua
								</a>
							</li>
						</ul>
					</div>
				</div>
			</div>
		</div>
	</div>
</div>