<div class="block-box" data-view="application/index/index">
    <div class="block-content">
        <?php echo $this->render('application/left-menu'); ?>
        <div class="main border-left">
            <div class="block-banner">
                <div class="banner-sidebar owl-carousel owl-theme">
                    <div class="banner-sidebar-item item">
                        <a href="">
                            <img src="http://jysk.vn//DATA/AdvImg//20160927/jysk-favourist_400x1140.jpg">
                        </a>
                    </div>
                    <div class="banner-sidebar-item item">
                        <a href="">
                            <img src="https://uma.vn/media/wysiwyg/bannerslider/b/a/xbanner-home-slide-student-collection-desktop-vi.jpg.pagespeed.ic.9vFLPqB1m2.webp">
                        </a>
                    </div>
                    <div class="banner-sidebar-item item">
                        <a href="">
                            <img src="https://uma.vn/media/wysiwyg/bannerslider/b/a/xbanner-home-slider-combo-sieutk-desktop-vi.jpg.pagespeed.ic.LtfeXAmOb-.webp">
                        </a>
                    </div>
                </div>
            </div>
            <div class="list-items">
                <div class="item">
                    <div class="item-view">
                        <ul class="item-fluid">
                            <li class="img">
                                <div class="thumbnails">
                                    <a href="/san-pham/bo-phong-ngu-cao-cap-703/" class="thumbnail">
                                        <img src="https://www.kymdan.com/attachment.do?file=attachment/49/SYMMETRIC_avatar_384x230_384x288.jpg" title="Bộ phòng ngủ cao cấp 703" alt="Bộ phòng ngủ cao cấp 703">
                                    </a>
                                </div>
                            </li>
                            <li>
                                <h2 class="entry-title">
                                    <a title="Bộ phòng ngủ cao cấp 703" href="/san-pham/bo-phong-ngu-cao-cap-703/">Bộ phòng ngủ cao cấp 703</a>
                                </h2>
                            </li>
                            <li class="price-sale"> 122,000,000 vnđ</li>
                            <li class="price-old"> 125,000,000 vnd</li>
                            <li>
                                <a style="display:block;line-height:15px;color:#ffffff" rel="nofollow" href="/san-pham/bo-phong-ngu-cao-cap-703/" class="text-right mybutton">
                                    <i class="fa fa-shopping-cart" aria-hidden="true"></i> Đặt mua
                                </a>
                            </li>
                        </ul>
                    </div>
                </div>
                <div class="item">
                    <div class="item-view">
                        <ul class="item-fluid">
                            <li class="img">
                                <div class="thumbnails">
                                    <a href="/san-pham/bo-phong-ngu-cao-cap-703/" class="thumbnail">
                                        <img src="https://www.kymdan.com/attachment.do?file=attachment/44/bed_light_new(l)_384x288.jpg" title="Bộ phòng ngủ cao cấp 703" alt="Bộ phòng ngủ cao cấp 703">
                                    </a>
                                </div>
                            </li>
                            <li>
                                <h2 class="entry-title">
                                    <a title="Bộ phòng ngủ cao cấp 703" href="/san-pham/bo-phong-ngu-cao-cap-703/">Bộ phòng ngủ cao cấp 703</a>
                                </h2>
                            </li>
                            <li class="price-sale"> 122,000,000 vnđ</li>
                            <li class="price-old"> 125,000,000 vnd</li>
                            <li>
                                <a style="display:block;line-height:15px;color:#ffffff" rel="nofollow" href="/san-pham/bo-phong-ngu-cao-cap-703/" class="text-right mybutton">
                                    <i class="fa fa-shopping-cart" aria-hidden="true"></i> Đặt mua
                                </a>
                            </li>
                        </ul>
                    </div>
                </div>
                <div class="item">
                    <div class="item-view">
                        <ul class="item-fluid">
                            <li class="img">
                                <div class="thumbnails">
                                    <a href="/san-pham/bo-phong-ngu-cao-cap-703/" class="thumbnail">
                                        <img src="https://www.kymdan.com/attachment.do?file=attachment/6309/DIAMOND_avatar_384x288.jpg" title="Bộ phòng ngủ cao cấp 703" alt="Bộ phòng ngủ cao cấp 703">
                                    </a>
                                </div>
                            </li>
                            <li>
                                <h2 class="entry-title">
                                    <a title="Bộ phòng ngủ cao cấp 703" href="/san-pham/bo-phong-ngu-cao-cap-703/">Bộ phòng ngủ cao cấp 703</a>
                                </h2>
                            </li>
                            <li class="price-sale"> 122,000,000 vnđ</li>
                            <li class="price-old"> 125,000,000 vnd</li>
                            <li>
                                <a style="display:block;line-height:15px;color:#ffffff" rel="nofollow" href="/san-pham/bo-phong-ngu-cao-cap-703/" class="text-right mybutton">
                                    <i class="fa fa-shopping-cart" aria-hidden="true"></i> Đặt mua
                                </a>
                            </li>
                        </ul>
                    </div>
                </div>
                <div class="item">
                    <div class="item-view">
                        <ul class="item-fluid">
                            <li class="img">
                                <div class="thumbnails">
                                    <a href="/san-pham/bo-phong-ngu-cao-cap-703/" class="thumbnail">
                                        <img src="https://www.kymdan.com/attachment.do?file=attachment/500/bed_rainbow(l)_384x288.jpg" title="Bộ phòng ngủ cao cấp 703" alt="Bộ phòng ngủ cao cấp 703">
                                    </a>
                                </div>
                            </li>
                            <li>
                                <h2 class="entry-title">
                                    <a title="Bộ phòng ngủ cao cấp 703" href="/san-pham/bo-phong-ngu-cao-cap-703/">Bộ phòng ngủ cao cấp 703</a>
                                </h2>
                            </li>
                            <li class="price-sale"> 122,000,000 vnđ</li>
                            <li class="price-old"> 125,000,000 vnd</li>
                            <li>
                                <a style="display:block;line-height:15px;color:#ffffff" rel="nofollow" href="/san-pham/bo-phong-ngu-cao-cap-703/" class="text-right mybutton">
                                    <i class="fa fa-shopping-cart" aria-hidden="true"></i> Đặt mua
                                </a>
                            </li>
                        </ul>
                    </div>
                </div>
                <div class="item">
                    <div class="item-view">
                        <ul class="item-fluid">
                            <li class="img">
                                <div class="thumbnails">
                                    <a href="/san-pham/bo-phong-ngu-cao-cap-703/" class="thumbnail">
                                        <img src="https://www.kymdan.com/attachment.do?file=attachment/49/SYMMETRIC_avatar_384x230_384x288.jpg" title="Bộ phòng ngủ cao cấp 703" alt="Bộ phòng ngủ cao cấp 703">
                                    </a>
                                </div>
                            </li>
                            <li>
                                <h2 class="entry-title">
                                    <a title="Bộ phòng ngủ cao cấp 703" href="/san-pham/bo-phong-ngu-cao-cap-703/">Bộ phòng ngủ cao cấp 703</a>
                                </h2>
                            </li>
                            <li class="price-sale"> 122,000,000 vnđ</li>
                            <li class="price-old"> 125,000,000 vnd</li>
                            <li>
                                <a style="display:block;line-height:15px;color:#ffffff" rel="nofollow" href="/san-pham/bo-phong-ngu-cao-cap-703/" class="text-right mybutton">
                                    <i class="fa fa-shopping-cart" aria-hidden="true"></i> Đặt mua
                                </a>
                            </li>
                        </ul>
                    </div>
                </div>
                <div class="item">
                    <div class="item-view">
                        <ul class="item-fluid">
                            <li class="img">
                                <div class="thumbnails">
                                    <a href="/san-pham/bo-phong-ngu-cao-cap-703/" class="thumbnail">
                                        <img src="https://www.kymdan.com/attachment.do?file=attachment/6368/RULER_avatar_384x288.jpg" title="Bộ phòng ngủ cao cấp 703" alt="Bộ phòng ngủ cao cấp 703">
                                    </a>
                                </div>
                            </li>
                            <li>
                                <h2 class="entry-title">
                                    <a title="Bộ phòng ngủ cao cấp 703" href="/san-pham/bo-phong-ngu-cao-cap-703/">Bộ phòng ngủ cao cấp 703</a>
                                </h2>
                            </li>
                            <li class="price-sale"> 122,000,000 vnđ</li>
                            <li class="price-old"> 125,000,000 vnd</li>
                            <li>
                                <a style="display:block;line-height:15px;color:#ffffff" rel="nofollow" href="/san-pham/bo-phong-ngu-cao-cap-703/" class="text-right mybutton">
                                    <i class="fa fa-shopping-cart" aria-hidden="true"></i> Đặt mua
                                </a>
                            </li>
                        </ul>
                    </div>
                </div>
                <div class="item">
                    <div class="item-view">
                        <ul class="item-fluid">
                            <li class="img">
                                <div class="thumbnails">
                                    <a href="/san-pham/bo-phong-ngu-cao-cap-703/" class="thumbnail">
                                        <img src="https://www.kymdan.com/attachment.do?file=attachment/500/bed_rainbow(l)_384x288.jpg" title="Bộ phòng ngủ cao cấp 703" alt="Bộ phòng ngủ cao cấp 703">
                                    </a>
                                </div>
                            </li>
                            <li>
                                <h2 class="entry-title">
                                    <a title="Bộ phòng ngủ cao cấp 703" href="/san-pham/bo-phong-ngu-cao-cap-703/">Bộ phòng ngủ cao cấp 703</a>
                                </h2>
                            </li>
                            <li class="price-sale"> 122,000,000 vnđ</li>
                            <li class="price-old"> 125,000,000 vnd</li>
                            <li>
                                <a style="display:block;line-height:15px;color:#ffffff" rel="nofollow" href="/san-pham/bo-phong-ngu-cao-cap-703/" class="text-right mybutton">
                                    <i class="fa fa-shopping-cart" aria-hidden="true"></i> Đặt mua
                                </a>
                            </li>
                        </ul>
                    </div>
                </div>
                <div class="item">
                    <div class="item-view">
                        <ul class="item-fluid">
                            <li class="img">
                                <div class="thumbnails">
                                    <a href="/san-pham/bo-phong-ngu-cao-cap-703/" class="thumbnail">
                                        <img src="https://www.kymdan.com/attachment.do?file=attachment/500/bed_rainbow(l)_384x288.jpg" title="Bộ phòng ngủ cao cấp 703" alt="Bộ phòng ngủ cao cấp 703">
                                    </a>
                                </div>
                            </li>
                            <li>
                                <h2 class="entry-title">
                                    <a title="Bộ phòng ngủ cao cấp 703" href="/san-pham/bo-phong-ngu-cao-cap-703/">Bộ phòng ngủ cao cấp 703</a>
                                </h2>
                            </li>
                            <li class="price-sale"> 122,000,000 vnđ</li>
                            <li class="price-old"> 125,000,000 vnd</li>
                            <li>
                                <a style="display:block;line-height:15px;color:#ffffff" rel="nofollow" href="/san-pham/bo-phong-ngu-cao-cap-703/" class="text-right mybutton">
                                    <i class="fa fa-shopping-cart" aria-hidden="true"></i> Đặt mua
                                </a>
                            </li>
                        </ul>
                    </div>
                </div>
                <div class="item">
                    <div class="item-view">
                        <ul class="item-fluid">
                            <li class="img">
                                <div class="thumbnails">
                                    <a href="/san-pham/bo-phong-ngu-cao-cap-703/" class="thumbnail">
                                        <img src="https://www.kymdan.com/attachment.do?file=attachment/6368/RULER_avatar_384x288.jpg" title="Bộ phòng ngủ cao cấp 703" alt="Bộ phòng ngủ cao cấp 703">
                                    </a>
                                </div>
                            </li>
                            <li>
                                <h2 class="entry-title">
                                    <a title="Bộ phòng ngủ cao cấp 703" href="/san-pham/bo-phong-ngu-cao-cap-703/">Bộ phòng ngủ cao cấp 703</a>
                                </h2>
                            </li>
                            <li class="price-sale"> 122,000,000 vnđ</li>
                            <li class="price-old"> 125,000,000 vnd</li>
                            <li>
                                <a style="display:block;line-height:15px;color:#ffffff" rel="nofollow" href="/san-pham/bo-phong-ngu-cao-cap-703/" class="text-right mybutton">
                                    <i class="fa fa-shopping-cart" aria-hidden="true"></i> Đặt mua
                                </a>
                            </li>
                        </ul>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <div class="block-info">
        <div class="block-info-head">
            <h3>Góc tư vấn</h3>
        </div>
        <div class="block-info-content">
            <div class="list-items">
                <div class="item">
                    <a href="<?php echo SITE_URL; ?>tin-tuc">
                        <div class="item-thumbnails">
                            <img src="http://noithatnhapkhau.net.vn/assets/sofa-da-S-368-.jpg">
                        </div>
                        <div class="item-text">
                            <div class="item-title">Sofa phòng khách S368 nhập khẩu tuyệt đẹp giá rẻ</div>
                            <div class="item-desc">Mẫu sofa phòng khách S368 kết hợp với hệ bàn trà và kệ tivi 579 mang đến cho không gian phòng khách gia đình bạn sự sang trọng và tiện nghi.</div>
                        </div>
                    </a>
                </div>
                <div class="item">
                    <a href="<?php echo SITE_URL; ?>tin-tuc">
                        <div class="item-thumbnails">
                            <img src="http://noithatnhapkhau.net.vn/assets/sofa-da-S-368-.jpg">
                        </div>
                        <div class="item-text">
                            <div class="item-title">Sofa phòng khách S368 nhập khẩu tuyệt đẹp giá rẻ</div>
                            <div class="item-desc">Mẫu sofa phòng khách S368 kết hợp với hệ bàn trà và kệ tivi 579 mang đến cho không gian phòng khách gia đình bạn sự sang trọng và tiện nghi.</div>
                        </div>
                    </a>
                </div>
                <div class="item">
                    <a href="<?php echo SITE_URL; ?>tin-tuc">
                        <div class="item-thumbnails">
                            <img src="http://noithatnhapkhau.net.vn/assets/sofa-da-S-368-.jpg">
                        </div>
                        <div class="item-text">
                            <div class="item-title">Sofa phòng khách S368 nhập khẩu tuyệt đẹp giá rẻ</div>
                            <div class="item-desc">Mẫu sofa phòng khách S368 kết hợp với hệ bàn trà và kệ tivi 579 mang đến cho không gian phòng khách gia đình bạn sự sang trọng và tiện nghi.</div>
                        </div>
                    </a>
                </div>
                <div class="item">
                    <a href="<?php echo SITE_URL; ?>tin-tuc">
                        <div class="item-thumbnails">
                            <img src="http://noithatnhapkhau.net.vn/assets/sofa-da-S-368-.jpg">
                        </div>
                        <div class="item-text">
                            <div class="item-title">Sofa phòng khách S368 nhập khẩu tuyệt đẹp giá rẻ</div>
                            <div class="item-desc">Mẫu sofa phòng khách S368 kết hợp với hệ bàn trà và kệ tivi 579 mang đến cho không gian phòng khách gia đình bạn sự sang trọng và tiện nghi.</div>
                        </div>
                    </a>
                </div>
            </div>
        </div>
    </div>
</div>