<div class="block-box">
	<div class="block-content">
		<div class="left">
			<div class="widget">
				<div class="widget-inner">
					<h3>Danh mục sản phẩm</h3>
					<div class="widget-border-top"></div>
					<div class="widget-content">
						<ul>
							<li>
								<a href="<?php echo SITE_URL; ?>the-loai/">Nội thất phòng ngủ</a>
							</li>
							<li>
								<a>Nội thất phong cách Hàn Quốc</a>
							</li>
							<li>
								<a>Nội thất tân cổ điển trắng</a>
							</li>
							<li>
								<a>Nội thất phong cách Hàn Quốc</a>
							</li>
							<li>
								<a>Nội thất tân cổ điển trắng</a>
							</li>
							<li>
								<a>Nội thất phong cách Hàn Quốc</a>
							</li>
						</ul>
					</div>
				</div>
			</div>
			<div class="widget-news">
				<div class="box-head">TIN TỨC MỚI</div>
				<div class="box-content">
					<ul>
						<li>
							<div class="img">
								<img src="http://static.megavita.vn/uploads/content/2017/03/01/thumbs/116x116_1488334000.1886.jpg">
							</div>
							<div class="detail">
								<div class="title">
									<a href="<?php echo SITE_URL; ?>tin-tuc">Top 5 cách chống lão hoá da mặt cho tuổi 30</a>
								</div>
								<div class="time">
									<div class="date">28/02/2017</div>
								</div>
							</div>
						</li>
						<li>
							<div class="img">
								<img src="http://static.megavita.vn/uploads/content/2017/03/01/thumbs/116x116_1488334000.1886.jpg">
							</div>
							<div class="detail">
								<div class="title">
									<a href="<?php echo SITE_URL; ?>tin-tuc">Top 5 cách chống lão hoá da mặt cho tuổi 30</a>
								</div>
								<div class="time">
									<div class="date">28/02/2017</div>
								</div>
							</div>
						</li>
						<li>
							<div class="img">
								<img src="http://static.megavita.vn/uploads/content/2017/03/01/thumbs/116x116_1488334000.1886.jpg">
							</div>
							<div class="detail">
								<div class="title">
									<a href="<?php echo SITE_URL; ?>tin-tuc">Top 5 cách chống lão hoá da mặt cho tuổi 30</a>
								</div>
								<div class="time">
									<div class="date">28/02/2017</div>
								</div>
							</div>
						</li>
						<li>
							<div class="img">
								<img src="http://static.megavita.vn/uploads/content/2017/03/01/thumbs/116x116_1488334000.1886.jpg">
							</div>
							<div class="detail">
								<div class="title">
									<a>Top 5 cách chống lão hoá da mặt cho tuổi 30</a>
								</div>
								<div class="time">
									<div class="date">28/02/2017</div>
								</div>
							</div>
						</li>
					</ul>
				</div>
			</div>
		</div>
		<div class="main border-left">
			<div class="main-title">
				<h3>Cách sử dụng collagen đúng cách và hiệu quả nhất</h3>
				<p>Ngày đăng: 02/06/2015 lúc 09:50:42 | Đã xem: 2151 | Theo : Quản trị viên</p>
			</div>
			<div class="main-content">
				<p> Collagen có dạng sợi dài nhỏ, phần lớn được thấy trong các mô xơ như dây chằng, gân hay da và cũng có nhiều trong giác mạc, xương, sụn... Collagen có chức năng kết nối các mô trong cơ thể lại với nhau, nếu không có collagen thì các phần trong cơ thể không thể liên kết lại với nhau được, mà trở thành các phần rời rạc.</p>
				<p>Được mọi người sử dụng và bán rộng rải trên thị trường. Không chỉ chăm sóc sức khỏe, mà collagen còn được biết là thần dược trong việc chăm sóc sắc đẹp, lưu giữ mãi tuổi thanh xuân.</p>
				<div><img style="display: block; margin-left: auto; margin-right: auto;" src="http://static.megavita.vn/uploads/content/2016/03/11/1457665334.3903.png" alt=""></div>
			</div>
			<div class="product-sample">
				<div class="title">Sản phẩm cùng chuyên mục</div>
				<div class="box-products">
					<ul>
						<li>
							<div class="img">
								<img src="https://www.kymdan.com/attachment.do?file=attachment/49/SYMMETRIC_avatar_384x230_384x288.jpg">
							</div>
							<div class="info">
								<div class="title">Bộ phòng ngủ cao cấp 703</div>
								<div class="price">512.300 vnđ</div>
							</div>
						</li>
						<li>
							<div class="img">
								<img src="https://www.kymdan.com/attachment.do?file=attachment/49/SYMMETRIC_avatar_384x230_384x288.jpg">
							</div>
							<div class="info">
								<div class="title">Bộ phòng ngủ cao cấp 703</div>
								<div class="price">512.300 vnđ</div>
							</div>
						</li>
						<li>
							<div class="img">
								<img src="https://www.kymdan.com/attachment.do?file=attachment/49/SYMMETRIC_avatar_384x230_384x288.jpg">
							</div>
							<div class="info">
								<div class="title">Bộ phòng ngủ cao cấp 703</div>
								<div class="price">512.300 vnđ</div>
							</div>
						</li>
						<li>
							<div class="img">
								<img src="https://www.kymdan.com/attachment.do?file=attachment/49/SYMMETRIC_avatar_384x230_384x288.jpg">
							</div>
							<div class="info">
								<div class="title">Bộ phòng ngủ cao cấp 703</div>
								<div class="price">512.300 vnđ</div>
							</div>
						</li>
					</ul>
				</div>
			</div>
		</div>
	</div>
</div>