<div class="data-view" data-view="administrator/category/create">
    <div class="col-xs-9">
        <div class="widget-box">
            <div class="widget-body">
                <div class="widget-main">
                    <div id="fuelux-wizard-container" class="no-steps-container">
                        <div class="step-content pos-rel">
                            <div class="step-pane active" data-step="1">
                                <h3 class="lighter block green">Nhập thông tin</h3>
                                <form class="form-horizontal" id="sample-form" method="post">
                                    <?php if(!empty($this->params['error'])):?>
                                        <div class="alert alert-danger">
                                            <button type="button" class="close" data-dismiss="alert">
                                                <i class="ace-icon fa fa-times"></i>
                                            </button>
                                            <strong>
                                                <i class="ace-icon fa fa-times"></i>
                                                Oh snap!
                                            </strong>
                                            <?php echo $this->params['error']?>
                                            <br>
                                        </div>
                                    <?php endif;?>
                                    <div class="form-group">
                                        <label for="inputWarning" class="col-xs-12 col-sm-3 control-label no-padding-right">Tên danh mục</label>
                                        <div class="col-xs-12 col-sm-5">
                                            <span class="block input-icon input-icon-right">
                                                <input type="text" class="width-100" name="cate_name" placeholder="Nhập tên danh mục"
                                                       value="<?php echo empty($this->params['cate_name']) ? '' : $this->params['cate_name']?>">
                                            </span>
                                        </div>
                                    </div>

                                    <div class="form-group">
                                        <label for="inputError" class="col-xs-12 col-sm-3 col-md-3 control-label no-padding-right">Danh mục cha</label>
                                        <div class="col-xs-12 col-sm-5">
                                            <span class="block input-icon input-icon-right">
                                                <select class="select-picker width-100" data-live-search="true" name="parent_id">
                                                    <option value="0">
                                                            Chọn danh mục
                                                    </option>
                                                    <?php if (!empty($this->parent['rows'])):
                                                        foreach ($this->parent['rows'] as $row):
                                                            ?>
                                                         <option value="<?php echo $row['cate_id'];?>">
                                                        <?php
                                                        if ($row['parent_id'] == 0) {
                                                            echo '<a href="javascript:;"><b>' . $row['cate_name'] . '</b></a>';
                                                        } else {
                                                            $temp = substr_count($row['full_sort'], ':');
                                                            echo str_repeat('&nbsp;&nbsp;&nbsp;', $temp);
                                                            echo '&#x21b3;&nbsp;&nbsp;';
                                                            echo '<a href="javascript:;"><b>' . $row['cate_name'] . '</b></a>';
                                                        }
                                                        ?>
                                                            </option>
                                                            <?php endforeach;
                                                        endif;
                                                        ?>
                                                </select>
                                            </span>
                                        </div>
                                    </div>

                                    <div class="form-group">
                                        <label for="inputWarning" class="col-xs-12 col-sm-3 control-label no-padding-right">Độ ưu tiên</label>
                                        <div class="col-xs-12 col-sm-5">
                                            <span class="block input-icon input-icon-right">
                                                <input type="text" class="width-100" name="sort" placeholder="Nhập độ ưu tiên hiển thị"
                                                       value="<?php echo empty($this->params['sort']) ? '' : $this->params['sort']?>">
                                            </span>
                                        </div>
                                    </div>
                                    <hr>
                                    <div class="center">
                                        <button class="btn btn-success" type="submit">
                                            <i class="ace-icon fa fa-save"></i>
                                            Tạo
                                        </button>
                                    </div>
                                </form>
                            </div>
                        </div>
                    </div
                </div><!-- /.widget-main -->
            </div><!-- /.widget-body -->
        </div>
    </div>
</div>