<div data-view="administrator/category/index">
    <div class="col-item">
        <form method="get">
            <div class="rows" style="border-bottom: none; border-top: 1px solid #ddd">
                <div class="col-lg-2 pull-left" style="margin-top: 25px">
                    <div id="editable-sample_length" class="dataTables_length no-padding">
                        <a class="btn btn-success" href="<?php echo $this->Url('administratorCategory', ['action'=>'create'])?>"><i class="icon-plus-sign-alt"></i> Thêm</a>
                    </div>
                </div>
                <div class="search-product">
                    <div class="search-title">
                        <div class="search-title-block">
                            <input name="search" class="search-product-title" type="text" value="<?php echo !empty($this->params['search']) ? $this->params['search'] : ''?>" placeholder="Tìm kiếm theo tên">
                            <button class="search-products" type="submit">
                                <i class="icon-search"></i>
                            </button>
                        </div>
                    </div>
                </div>
            </div>
            <table style="margin-bottom: 0" class="table table-striped table-bordered table-hover">
                <thead>
                <tr>
                    <th class="center"><span class="icon icon-list"> ID</th>
                    <th class="center"><span class="icon icon-list-alt"></span> Tên</th>
                    <th class="center"><span class="icon icon-calendar"></span> Ngày tạo</th>
                    <th class="center"><span class="icon icon-user"></span> Người tạo</th>
<!--                    <th class="center"><span class="icon icon-random"></span> Trạng thái</th>-->
                    <th class="center"><span class="icon icon-gears"></span> Tùy chỉnh</th>
                </tr>
                </thead>
                <tbody>
                <?php if(!empty($this->categories['rows'])):
                    foreach ($this->categories['rows'] as $category):
                        ?>
                        <tr>
                            <td class="center">
                                <b>
                                    <a href="javascript:;">
                                        <?php echo $category['cate_id']?>
                                    </a>
                                </b>
                            </td>
                            <td>
                                <?php
                                if ($category['parent_id'] == 0) {
                                    echo '<a href="javascript:;"><b>' . $category['cate_name'] . '</b></a>';
                                } else {
                                    $temp = substr_count($category['full_sort'], ':');
                                    echo str_repeat('&nbsp;&nbsp;&nbsp;', $temp);
                                    echo '&#x21b3;&nbsp;&nbsp;';
                                    echo '<a href="javascript:;"><b>' . $category['cate_name'] . '</b></a>';
                                }
                                ?>
                            </td>
                            <td class="center"><?php echo date('Y-m-d', $category['created_date']);?></td>
                            <td class="center"><?php echo empty($this->users[$category['user_created']]) ? '' : $this->users[$category['user_created']]['full_name']?></td>
<!--                            <td class="center">-->
<!--                                --><?php //if($category['status'] == APP\Model\Category::CATEGORY_STATUS_ACTIVE):?>
<!--                                    <a class="btn-circle" href="javascript:;" data-toggle="tooltip" title="Hiển thị"><i class="ico icon-check"></i></a>-->
<!--                                --><?php //else:?>
<!--                                    <a class="btn-circle" href="javascript:;" data-toggle="tooltip" title="Ẩn"><i class="ico icon-remove"></i></a>-->
<!--                                --><?php //endif;?>
<!--                            </td>-->
                            <td class="center">
                                <a class="btn-circle" data-toggle="tooltip" title="Cập nhật" href="<?php echo $this->Url('administratorCategory', ['action'=>'edit', 'id' => $category['cate_id']])?>"><i class="icon icon-pencil"></i></a>
                                <a class="btn-circle delete" data-toggle="tooltip" rel="<?php echo $category['cate_id']?>" title="Xóa danh mục"><i class="icon icon-trash"></i></a>
                            </td>
                        </tr>
                    <?php endforeach;?>
                    <?php endif;?>
                </tbody>
            </table>
            <?php
            $params = $this->params;
            $params['controller'] = $params['strController'];
            $paging = $this->pagingText($params);
            if(!empty($paging)){
                echo $paging;
            }
            ?>
        </form>
    </div>
</div>