<div class="row" data-view="administrator/category/index">
    <div class="col-xs-12">
        <div class="col-sx-12" style="margin-bottom: 5px">
            <a class="btn btn-xs btn-success" href="<?php echo $this->Url('administratorCategory', ['action'=>'create'])?>">
                <i class="ace-icon fa fa-plus">
                    Thêm
                </i>
            </a>
        </div>
        <table id="simple-table" class="table  table-bordered table-hover">
            <thead>
            <tr>
                <th class="center"><span class="fa fa-list"> ID</th>
                <th class="center"><span class="fa fa-list-alt"></span> Tên</th>
                <th class="center"><span class="fa fa-calendar"></span> Ngày tạo</th>
                <th class="center"><span class="fa fa-user"></span> Người tạo</th>
                <th class="center"><span class="fa fa-gears"></span> Tùy chỉnh</th>
            </tr>
            </thead>
            <tbody>
                <?php if(!empty($this->categories['rows'])):
                foreach ($this->categories['rows'] as $category):
                    ?>
                    <tr>
                        <td class="center">
                            <b>
                                <a href="javascript:;">
                                    <?php echo $category['cate_id']?>
                                </a>
                            </b>
                        </td>
                        <td>
                            <?php
                            if ($category['parent_id'] == 0) {
                                echo '<a href="javascript:;"><b>' . $category['cate_name'] . '</b></a>';
                            } else {
                                $temp = substr_count($category['full_sort'], ':');
                                echo str_repeat('&nbsp;&nbsp;&nbsp;', $temp);
                                echo '&#x21b3;&nbsp;&nbsp;';
                                echo '<a href="javascript:;"><b>' . $category['cate_name'] . '</b></a>';
                            }
                            ?>
                        </td>
                        <td class="center"><?php echo date('Y-m-d', $category['created_date']);?></td>
                        <td class="center"><?php echo empty($this->users[$category['user_created']]) ? '' : $this->users[$category['user_created']]['full_name']?></td>
                        <td class="center">
                            <div class="hidden-sm hidden-xs btn-group">
                                <a class="btn btn-xs btn-info" data-toggle="tooltip" title="Cập nhật" href="<?php echo $this->Url('administratorCategory', ['action'=>'edit', 'id' => $category['cate_id']])?>"><i class="ace-icon fa fa-pencil bigger-120"></i></a>
                                <a class="btn btn-xs btn-danger delete" data-toggle="tooltip" rel="<?php echo $category['cate_id']?>" title="Xóa danh mục"><i class="ace-icon fa fa-trash-o bigger-120"></i></a>
                            </div>
                        </td>
                    </tr>
                <?php endforeach;?>
            <?php endif;?>
            </tbody>
        </table>
        <?php
        $params = $this->params;
        $params['controller'] = $params['strController'];
        $paging = $this->pagingText($params);
        if(!empty($paging)){
            echo $paging;
        }
        ?>
    </div>
</div>