<div class="data-view" data-view="administrator/category/test">
    <div class="col-xs-9">
        <div class="widget-box">
            <div class="widget-body">
                <div class="widget-main">
                    <div id="fuelux-wizard-container" class="no-steps-container">
                        <div class="step-content pos-rel">
                            <div class="step-pane active" data-step="1">
                                <h3 class="lighter block green">Nhập thông tin</h3>
                                <button class="btn btn-xs btn-success test">
                                        ahihi
                                </button>
                            </div>
                        </div>
                    </div
                </div><!-- /.widget-main -->
            </div><!-- /.widget-body -->
        </div>
    </div>
</div>