<?php
    $country_id = !empty($this->params['country_id']) ? $this->params['country_id']: (empty($this->brand['country_id']) ? '' : $this->brand['country_id']);
?>

<div class="data-view" data-view="administrator/brand/edit">
    <div class="cat-content">
        <form name="form" class="form" method="post">
            <div class="col-cate-left" style="margin-bottom: 40px">
                <?php if(!empty($this->params['error'])):?>
                    <h4 class="header red lighter bigger" style="margin-top: -15px; margin-bottom: 30px">
                        <center>--------<b>ERROR</b>----------</br></center>
                        <center><?php echo $this->params['error']?></center>
                    </h4>
                <?php endif;?>
                <span class="block input-icon input-icon-right">
                    <label>Tên nhãn hiệu <span class="red">(*)</span></label>
                    <input name="brand_name" type="text" class="span12" placeholder="Nhập tên nhãn hiệu" required
                           value="<?php echo empty($this->params['brand_name']) ? $this->brand['brand_name'] : $this->params['brand_name'];?>"
                    >
                </span>

                <?php if($this->countries):?>
                    <span class="block input-icon input-icon-right">
                    <label>Nguồn gốc - xuất xứ <span class="red">(*)</span></label>
                    <select class="select-picker" data-live-search="true" name="country_id">
                        <?php foreach ($this->countries['rows'] as $row): ?>
                            <option value="<?php echo $row['country_id'];?>" <?php if($country_id == $row['country_id']):?> selected<?php endif;?>>
                                <?php echo $row['country_name'];?>
                            </option>
                        <?php endforeach;?>
                    </select>
                </span>
                <?php endif;?>

                <span class="block input-icon input-icon-right" style="margin-top: 10px">
                    <button class="btn btn-success" name="save"><i class="icon icon-save"></i> Lưu</button>
                </span>
            </div>
        </form>
    </div>
</div>